### ISSUE TITLE
[PANEL] Duplicating messages in chat window

### ISSUE THREAD

**Issue by xCausxn** [SpaceCP/Bugs#1]
Chat messages are sometimes duplicated in the chat message pane. 

http://puu.sh/lPAKi/c66a8c56fe.png

**Comment by MiniDigger** [comment]
+1

**Comment by Antariano** [comment]
Fixed in [Build 4](https://forums.spacecp.net/topic/303/open-beta-build-4-bugfixes-ui-improvements)
