### ISSUE TITLE
[Panel] Simple Plugin Manager Table Bug

### ISSUE THREAD

**Issue by renickbuettner** [SpaceCP/Bugs#10]
When I click on the "Name" or "Status" Fields, the table don't reorder.
<img width="655" alt="screenshot at dez 12 09-05-43" src="https://cloud.githubusercontent.com/assets/4125670/11760937/908c0a42-a0af-11e5-8930-6773e130edba.png">

**Comment by renickbuettner** [comment]
OS: OSX 10.11
Browser: Chrome

**Comment by Antariano** [comment]
Thanks, will look into it

**Comment by Antariano** [comment]
This has been fixed in build 6, which will land this weekend.
