### ISSUE TITLE
Players widget not displaying any online players or online operators 

### ISSUE THREAD

**Issue by Forge-Media** [SpaceCP/Bugs#102]
Pretty much as the title suggests. Once logged into the SpaceCP panel and connected to my MC server (Spigot 1.8.8) no players are shown as being online and the online operators list remains empty.

Also posted this on the SpaceCP forum here: https://forums.spacecp.net/topic/346/no-response-from-analytics-server/8

![injhkbv](https://cloud.githubusercontent.com/assets/7041755/12074912/5cbbd270-b166-11e5-9624-7d73c1460d3a.jpg)

**Comment by tlaundal** [comment]
Thanks for the report, but under the hood this is the same as #76, so I'll close this as a duplicate issue.
