### ISSUE TITLE
Chatting on spigot doesn't work

### ISSUE THREAD

**Issue by Antariano** [SpaceCP/Bugs#103]
Forked from https://github.com/SpaceCP/Bugs/issues/92

**Comment by tlaundal** [comment]
@ozzie1998, please paste the output from Houston when you start your server, try to chat on it, and stop it again. This is necessary for me to find out what's happening.

**Comment by tips48** [comment]
Works fine for me, Open Build 7 and MC 1.8.9, running the latest stable Spigot build

**Comment by ghost** [comment]
Yes, it just recently started to work, after updating houston, still
getting no CPU/RAM information, 0%.

**Comment by tips48** [comment]
Correct, refer to issue #116
