### ISSUE TITLE
Panel doesn't connect to daemon always 

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#104]
Since the panel continues to say that there is no connection to the server, is there a way to start the MC server from a Houston command?

Details
Windows 10 10586 (Nov. Update)
Houston build: 195
Latest Chrome Beta
Java 1.8_66

**Comment by tlaundal** [comment]
If you have set up the server from the panel, you can manage it from Houston by opening another console, go to houstons folder and do `node houston attach`. When you have selected a server here, you can start it by `.start`

**Comment by tlaundal** [comment]
However I guess the real issue here is that your server says it can't connect. Can you post the output of Houston here?

**Comment by SAIYAN48** [comment]
http://pastebin.com/u0sASQRh

**Comment by tlaundal** [comment]
I was able to reproduce this by restarting the daemon. It seems a bit undeterministic.

**Comment by tlaundal** [comment]
This is probably @antariano or @jamydev 's domain

**Comment by SAIYAN48** [comment]
Update: Using the Houston 198 Build (Open Beta 7) and Houston says it called back to SpaceCP, but the daemon keeps saying Connecting.

Daemon Log:
http://pastebin.com/aLBZh9dw

**Comment by SAIYAN48** [comment]
It seems to do this on every build that I use.

**Comment by JamyDev** [comment]
Got a new houston log for me? And check if `https://<serverip>:35566/ping` loads

**Comment by SAIYAN48** [comment]
First thing I had to do was to set the port to my open one. Log: http://pastebin.com/608XHtPs
Using the correct open port (2705) the ping does not load. Side Note: Totokaka had me test my connection to the Panel Service and said it was fine.

**Comment by JamyDev** [comment]
If the ping does not load (a certificate warning means it's loading) there's an issue on your end. Provide some aditional details, OS, Router config, (or is this on a server, what firewall service), eslinux status, anything that can help resolve it.

**Comment by SAIYAN48** [comment]
It kinda worked: http://imgur.com/uUIYQEG
Server OS: Windows 10 November update
My Os: WIn 10 build 14257.
Browser: Latest Chrome Beta
Java 1.8_66 on both computers
Port 2705 is open.

**Comment by JamyDev** [comment]
I said https, not http

**Comment by SAIYAN48** [comment]
That ping works too.
