### ISSUE TITLE
1.7.10 Server randomly getting disconnected from the panel.

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#107]
All working perfectly, after rebooting Houston the server would not reconnect. Apparently the jar file can't be found.

**Comment by tlaundal** [comment]
Thank for reporting this problem @ozzie1998, but we need some more information to solve it. Please answer the following questions:
How did you restart houston?
Did you see any errors on the panel?

We also need you to post the output from Houston when you experience this error. Please start Houston, check that it doesn't connect to SpaceCP, then stop houston by pressing `Ctrl` and `C` at the same time, then enter. Copy the everything houston has printed in this time, on windows with `cmd` you do this by right clicking and select Mark. Paste it in a reply here like this:

``````
```
<Paste here>
```
``````

**Comment by tlaundal** [comment]
Probably related to #104

**Comment by ghost** [comment]
I was not physically able to restart Houston, "has no method 'stop'"

**Comment by tlaundal** [comment]
You wrote "after rebooting Houston" in the first post. What do you mean by that? 

Is the error you posted taken from Houston or SpaceCP? 
Also, we are going to need the **full** Houston output, please follow my instructions above.

**Comment by ghost** [comment]
Its fixed now, I think it was a temp issue with my dedicated server, not completely sure.
