### ISSUE TITLE
Making a new server, does not always work as it should.

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#108]
Making a new server worked perfectly, once. After that it appeared to be very slow, after it was created, I entered the link to upload the files, that also took ages, (I used the same file server for creating the first server).

**Comment by tlaundal** [comment]
Thank for reporting this problem @ozzie1998, but we need some more information to solve it. Please answer the following questions:
When in the server creation process did things stop/slow down?
What link did you use for the server jar?
Did you see any errors on the panel?

We also need you to post the output from Houston when you experience this error. Please start Houston, try to create a server, then stop houston by pressing `Ctrl` and `C` at the same time, then enter. Copy the everything houston has printed in this time, on windows with `cmd` you do this by right clicking and select Mark. Paste it in a reply here like this:

``````
```
<Paste here>
```
``````

**Comment by ghost** [comment]
That all started working after the update. All fixed.
