### ISSUE TITLE
I cant use stop start etc

### ISSUE THREAD

**Issue by Helomi** [SpaceCP/Bugs#109]
Eng:
Hello i have problem, my houston server is started but i cant stop start restart etc with minecraft server. 
Slovak:
Ahoj, mám problém, s mojim houston serverom ktorý je zapnutý ale ja naňom nemôžem zapínať vypínať reštartovať atď minecraft server.

Screenshot:
https://ctrlv.cz/915x

**Comment by Helomi** [comment]
Oh, now it works.

**Comment by JamyDev** [comment]
Thanks, we found a small race condition. Going out in build 7!

**Comment by ghost** [comment]
also the same as Houston, "has no method 'stop'"

**Comment by ghost** [comment]
I'm sure this is separate? and when do you plan to deploy the fix?
