### ISSUE TITLE
[Panel] Schedules Table Bug

### ISSUE THREAD

**Issue by renickbuettner** [SpaceCP/Bugs#11]
<img width="1121" alt="screenshot at dez 12 09-09-33" src="https://cloud.githubusercontent.com/assets/4125670/11760952/44ffa66e-a0b0-11e5-8f89-06dda6dbdfff.png">

**Comment by MiniDigger** [comment]
When dealing with ui bugs it is extremely helpful to provide os and browser information. Possible even the resolution of the window.
You should add that

**Comment by renickbuettner** [comment]
Oh sorry :)
OS: OSX 10.11
Browser-window-width: 1384px
Browser: Chrome

**Comment by Antariano** [comment]
Thank you very much! Looking into it

**Comment by Antariano** [comment]
Build 6 brings improved responsiveness across the board
