### ISSUE TITLE
Viewing Logs Shows Gibberish

### ISSUE THREAD

**Issue by Katelyn-SN** [SpaceCP/Bugs#111]
Screenshot http://prntscr.com/9m277u

**Comment by ghost** [comment]
What text editor are you using? one that supports the .log format.

**Comment by JamyDev** [comment]
Might be sending out the gzipped data. Normally we convert that. I'll investigate

**Comment by PetieM** [comment]
It seems to only happen for prior days. The current day displays fine but anything after it displays exactly as in the screenshot.
![log](https://cloud.githubusercontent.com/assets/16453878/12120065/165877f0-b39d-11e5-8110-4a23244591a6.PNG)

**Comment by tlaundal** [comment]
I can confirm this is the gzipped data. When the panel requests the logs, the daemon replies with the files and their contents, but it doesn't unpack the `.log.gz` files.

**Comment by tips48** [comment]
Doesn't just happen in past days.  Here's some from 5 minutes ago: http://puu.sh/mkWBG/8585b9d41e.png

**Comment by Autopoietico** [comment]
Also happens to me: http://i.imgur.com/FpvFso5.png
