### ISSUE TITLE
Error thrown when sending commands when server is off

### ISSUE THREAD

**Issue by dsluijk** [SpaceCP/Bugs#112]
Not top priority, but an error is thrown when i send a random command in the console when the server is off (daemon IS running). On the panel itself you'll see the message: 'An error occured'. and spams the console. You might want to handle this error and show an message like 'Your server is not running!'.

Screenshots:
http://puu.sh/mjIa3/88ee3ff6e5.png
http://puu.sh/mjIbj/6921fa6aed.png

Client side:
Browser: Vivaldi 1.0.344.37 (Beta 2) (32-bit)
OS: windows 10 x64
Engine version: V8 4.7.80.25

Server side:
Digital ocean 5 GB droplet.
Processor: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz
OS: Ubuntu
/proc/version: Linux version 4.2.0-16-generic (buildd@lcy01-07) (gcc version 5.2.1 20151003 (Ubuntu 5.2.1-21ubuntu2) ) # 19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015

**Comment by tlaundal** [comment]
Thanks for the report, and my compliments for including all the information we need. 

This should be handled by the panel, we'll fix it.
