### ISSUE TITLE
Restart loop

### ISSUE THREAD

**Issue by jithatsonei** [SpaceCP/Bugs#113]
Houston will throw itself into a reboot loop if not bootstraped. Possibly have it exit on a signal where the crash handler won't be like 'Ayy reboot!' 

![image](https://cloud.githubusercontent.com/assets/12538482/12102280/68497b48-b2ff-11e5-81f6-b86312254a71.png)

(Also literally kills my CPU and wont close until I pkill from task manager)

On Win 10 64bit

**Comment by jithatsonei** [comment]
Forked from https://forums.spacecp.net/topic/353/added-a-new-demon-having-issues as well.

**Comment by tlaundal** [comment]
Related to #100. 

We should definitely avoid a loop like this.

**Comment by ghost** [comment]
this happened after running the command from the add new deamon page, is the command fucked?

**Comment by jithatsonei** [comment]
post your logs @ozzie1998

**Comment by ghost** [comment]
I am Performance-INC on the forum, my bad should have pointed that out.

**Comment by tlaundal** [comment]
This is fixed, and is ready for next deploy.
