### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by dsluijk** [SpaceCP/Bugs#114]
Start/stop/restart/settings icons not showing up. Working in microsoft edge. clearing cached files did not work.

http://puu.sh/mjK2K/15b736f3e0.jpg

Client side:
Browser: Vivaldi 1.0.344.37 (Beta 2) (32-bit)
OS: windows 10 x64
Engine version: V8 4.7.80.25

**Comment by dsluijk** [comment]
I think you misunderstood (my fault). It _is_ working on edge, but not on vivaldi.

**Comment by tlaundal** [comment]
Ahh, I see. We don't support vivaldi, sadly, as it is beta software.

**Comment by dsluijk** [comment]
That's a shame, i really like both vivaldi and spacecp :(
