### ISSUE TITLE
SpaceCP not working in internet explorer.

### ISSUE THREAD

**Issue by dsluijk** [SpaceCP/Bugs#115]
Internet explorer makes the app not accessible at all. No logic screen, this is just me surfing to app.spacecp.net.

ss:
http://puu.sh/mjKEs/161d89e107.jpg

Client side:
Browser: http://puu.sh/mjKId/231643e263.png
OS: windows 10 x64

**Comment by tlaundal** [comment]
This is will probably not be high priority. I had it working in IE some days ago, however there where a lot of graphics issues.

**Comment by tlaundal** [comment]
Seems to "work" for me, althought it's kind of messed up. I'm running IE 11.0.9600.17842.
I also had that promise error, but not the other one.

**Comment by jithatsonei** [comment]
Also translate that bottom error :V

**Comment by dsluijk** [comment]
@alucard0134 Sorry about that.

**DOM7011:** SpaceCP has disabled the cache, and a link to an help page from microsoft.
**HTML1300:** A navigation has taken place.
**SCRIPT5007**: Cannot use indexOf on a non-existing or empty variable. (or something like that, it's kind of hard to read, this one might be important).

**Comment by Antariano** [comment]
Thanks for the report

**Comment by Antariano** [comment]
To clarify, browser compatibility is high priority

**Comment by jithatsonei** [comment]
No no. Thanks for the report either way :). And I believe the promises thing is just a IE requirement but won't break the whole page (it can be silenced if the devs wish with ghetto spaghetti code)

**Comment by Antariano** [comment]
Found it! This one was nasty. :)
