### ISSUE TITLE
Analytics server does not always collect & publish for servers

### ISSUE THREAD

**Issue by tips48** [SpaceCP/Bugs#116]
http://puu.sh/mk2jg/942b70fb61.jpg

Running Build 7.  Server is Spigot running on Windows 10 x64.

**Comment by ghost** [comment]
Getting this too with bukkit on ubuntu. 15.0.4 or something, (on a OVH'd ubuntu)

**Comment by JadoJodo** [comment]
Also getting this issue on Ubuntu 15.10. It appears random as I've reinstalled 4x and 2 times it showed properly (I reinstalled for other reasons).

**Comment by ghost** [comment]
Are you using the houston plugin? Verify its working, and update Houston. I
have it working perfectly now after updating houston.

**Comment by tips48** [comment]
Will test when I get home.

**Comment by JadoJodo** [comment]
@ozzie1998 Says I'm up to date. I do see an error "Failed to load cron job" when Houston starts, but it calls to SpaceCP fine.

**Comment by JamyDev** [comment]
"Failed to load cron job" means that one of your time based schedules has an incorrect cron format.

**Comment by JadoJodo** [comment]
Relaunching Houston again (something I did a number of times last night) and the analytics are now showing up. Any idea why it would be random?

**Comment by JamyDev** [comment]
The reconnection from the stats daemon to your Houston instance isn't instant. It might be getting stuck sometimes, which is something I'll have to look into.

**Comment by JadoJodo** [comment]
It's worth noting that last night I was getting the described error here: CPU/Mem showing as 0/0. This morning, it had changed to the error indicating the analytics server was unavailable. Not sure how significant that is, but worth noting. Thanks, @JamyDev.

**Comment by JadoJodo** [comment]
The stats are once again not showing and are now displaying "No response from analytics server."

**Comment by ghost** [comment]
Well. It decided to stop working. This is separate from my issue. this is 0%, Not analysts server not responding!

**Comment by Antariano** [comment]
@ozzie1998 if you'd read the entire issue you'll see it is the same thing and people mentioning your error.
Meanwhile, #108 is still awaitng your feedback

**Comment by ghost** [comment]
Okay then... 108 has got my feedback now. Is this going to be fixed?

**Comment by Antariano** [comment]
Analytics should start working again as soon as we deploy the next build!

**Comment by ghost** [comment]
Yey! when do you plan to deploy the next build?
