### ISSUE TITLE
Banner is not created

### ISSUE THREAD

**Issue by tips48** [SpaceCP/Bugs#117]
Build 7, Windows 10 x64 Spigot server.  Might be because there are no players on the server, but the banner doesn't seem to generate when I logon to the server.

Says underneath the banner 'server is offline' when the server is recognized as online by the rest of the panel.

http://puu.sh/mk2sv/42bf2325b2.png

**Comment by Antariano** [comment]
The banner generates every 3 minutes, refresh and make sure it's a bug.

**Comment by tips48** [comment]
Confirmed bug.

**Comment by Antariano** [comment]
Some bugs snook into the new banner generator :) Fixed!
