### ISSUE TITLE
Log Positioning Broken in Safari

### ISSUE THREAD

**Issue by PetieM** [SpaceCP/Bugs#120]
The white box that logs appear in does not extend in Safari. The way elements are positioned on the page seems to be at fault here because scrolling down causes the new content to load over the existing instead of below it, as shown below:

![screen shot 2016-01-05 at 11 14 57 am](https://cloud.githubusercontent.com/assets/16453878/12120173/99096100-b39d-11e5-806b-7f666d8ccd77.png)

For reference, I'm using the most current build on CentOS 7. Let me know if you need any additional details.

**Comment by jithatsonei** [comment]
Curious if it's related to locales. Do you have en_US.UTF-8 generated?

**Comment by PetieM** [comment]
I'm not actually terribly familiar with locales and not sure how to check on CentOS. I know I haven't done it manually though so unless it gets generated automatically during install, it's unlikely present.

I can give you the output of locale if that helps though:

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by tlaundal** [comment]
I would think this is not related to locale, but rather issue #111.

**Comment by jithatsonei** [comment]
Ditto to @totokaka then.
(tl:dr panel doesn't unpack the compressed logs sent by Houston) I would say this is a duplicate

**Comment by PetieM** [comment]
Sorry if this wasn't clear. The issue being presented here isn't regarding the output itself but its positioning on the page. The screenshot provided was generated by simply scrolling down the page. Each additional chunk of the log that generated did so on top of the other content on the page instead of below it.

**Comment by ghost** [comment]
This is obviously not a duplicate...

**Comment by jithatsonei** [comment]
@ozzie1998 I realized that from PetieM comment. Apologies for my incorrect assumption.

**Comment by ghost** [comment]
Oh okay, didn't know you had.

**Comment by tlaundal** [comment]
I was able to reproduce this, and it is not linked to #111, as I first suspected.

Here are two screenshots with gibberish logs. As you can see, the logs continue out of the card.
![skjermbilde 2016-01-10 kl 14 03 21](https://cloud.githubusercontent.com/assets/817001/12221681/b14f9e3a-b7a5-11e5-9b0e-4f9b2ff64494.png)
When a new log file is opened, the card doesn't contain any log lines, they are just put under.
![skjermbilde 2016-01-10 kl 14 03 30](https://cloud.githubusercontent.com/assets/817001/12221682/b1817e6e-b7a5-11e5-8d13-2886f03eba6b.png)

Here are two similar screenshots with the undeployed fix for the gibberish logs.
![skjermbilde 2016-01-10 kl 14 18 13](https://cloud.githubusercontent.com/assets/817001/12221683/b18a78a2-b7a5-11e5-8c74-16eb5ba97f5e.png)
![skjermbilde 2016-01-10 kl 14 18 20](https://cloud.githubusercontent.com/assets/817001/12221684/b18bad8a-b7a5-11e5-9ca9-8f61588464aa.png)

**Comment by tlaundal** [comment]
This is now fixed.
