### ISSUE TITLE
App sending an invalid HSTS policy

### ISSUE THREAD

**Issue by dsluijk** [SpaceCP/Bugs#121]
Yes, I report everything I see.

The SpaceCP app is sending an invalid HSTS policy. No idea what it is or what it does, but it sends it :P. Server specs unrelated, so letting out. Won't be surprised if this issue gets closed.

Source:
https://www.ssllabs.com/ssltest/analyze.html?d=app.spacecp.net

Screenshot:
http://puu.sh/mkNrV/7a497e0d8f.png (orange part)

**Comment by JamyDev** [comment]
Interesting, thanks for bringing this to my attention.

**Comment by jithatsonei** [comment]
HSTS Headers:

strict-transport-security: max-age=31536000
strict-transport-security: max-age=63072000

Most likely just pasted twice in to different areas in the server block for app.spacecp.net
It is possible the includeSubdomains option enabled in the root domain server block, and has one in the  subdomain's block as well

EDIT: @JamyDev strict-transport-security: max-age=63072000 is the HSTS header for forums.spacecp.net and theres only one. I'd check on the spacecp.net server block (not any subdomains) for said includeSubdomains option on the add-header for HSTS, and if its there then feel free to delete the one inside app.spacecp.net. Then service nginx configtest for the good measure and badda bing budda boom fixed :p
