### ISSUE TITLE
There is no way to disable MCSignOnDoor

### ISSUE THREAD

**Issue by tips48** [SpaceCP/Bugs#122]
Open Build 7
Steps to reproduce:
1) Enable MCSignOnDoor in the panel and press save
2) (Optional) Close the prompt and reopen to ensure that the settings successfully saved
3) Open the prompt and uncheck the enable button.  The save button will be grayed out.
4) Close the prompt, and reopen to observe the enable button is checked again.

**Comment by tlaundal** [comment]
The only problem here is that the button is disabled when you uncheck the checkbox. Purely UI issue. 

If you trick with the HTML code you can enable the button again, and press it.

**Comment by Antariano** [comment]
Fixed
