### ISSUE TITLE
Slow connection

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#123]
The panel's connection to the daemon is **very** slow.

Specs:
Windows 10 1511
Java 1.8_66
Houston 198
Chrome Beta latest

**Comment by tlaundal** [comment]
Well this is not enough info to fix your issue.

Is everything slow? What parts in particular do you experience as slow?

How is your internet connection? Is the daemon on the same machine as you are viewing the panel?

**Comment by SAIYAN48** [comment]
For Example, when I press the button to start the server, it doesn't start immediately. After starting, it will take a bit longer to display the stats and logs. 

My internet is fine, I am viewing the panel from my computer and the Daemon is on the server comp.

**Comment by tlaundal** [comment]
Hmm, that is strange.
I am not experiencing such a problem.
Could you try to create a video or screencast where you show the problem, so we can get a better idea of exactly what's happening?

**Comment by SAIYAN48** [comment]
I'll try.

**Comment by tlaundal** [comment]
Also, @SAIYAN48, where in the world is your server located?

**Comment by SAIYAN48** [comment]
Same city that I'm in.

Here's some pics so far, taken at the same time:
http://imgur.com/a/VTteF

**Comment by tlaundal** [comment]
Well, could you tell me what city that is? Send me a PM if you want.

**Comment by SAIYAN48** [comment]
Forum PM Sent

**Comment by tlaundal** [comment]
I asked you on PM to send me a traceroute and ping of `app.spacecp.net` from the server machine running the daemon.

**Comment by SAIYAN48** [comment]
Latest build makes everything run smoothly :D
