### ISSUE TITLE
Plugin URL dialog looks strange

### ISSUE THREAD

**Issue by StaticcraftMC** [SpaceCP/Bugs#126]
When you click the plus button on the plugin page to add a plugin, the dialog box looks strange.
The text "Plugin URL" is moved up in the dialog box, so you can only see half of it.

**Comment by tlaundal** [comment]
Here is an image of how it looks when the input field is not highlighted
![plugin url box not highlighted](https://cloud.githubusercontent.com/assets/817001/12221987/393e01e4-b7ae-11e5-8d67-e245be783709.PNG)
And when it is highlighted, this is where it's strange
![plugin url box highlighted](https://cloud.githubusercontent.com/assets/817001/12221989/451aa350-b7ae-11e5-82b8-f31968d26320.PNG)

**Comment by Antariano** [comment]
Done!
