### ISSUE TITLE
Saving every ten seconds.

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#129]
Bukkit 1.7.10

xeoncraft: [16:01:01 INFO]: *\* [Saving] Rewards.bin
xeoncraft: [16:01:01 INFO]: *\* [Saving] Rewards.bin - SAVED
xeoncraft: [16:01:01 INFO]: *\* [Saving] Users.bin
xeoncraft: [16:01:01 INFO]: *\* [Saving] Users.bin - SAVED
xeoncraft: [16:01:01 INFO]: 1452114061847 Scheduling 10 seconds from now
xeoncraft: [16:01:11 INFO]: Sentury Working
xeoncraft: [16:01:11 INFO]: Sentury Running @ 1452114071850
xeoncraft: [16:01:11 INFO]: 1452114071850 TASK Sentury Running
xeoncraft: [16:01:11 INFO]: *\* [Saving] Rewards.bin
xeoncraft: [16:01:11 INFO]: *\* [Saving] Rewards.bin - SAVED
xeoncraft: [16:01:11 INFO]: *\* [Saving] Users.bin
xeoncraft: [16:01:11 INFO]: *\* [Saving] Users.bin - SAVED
xeoncraft: [16:01:11 INFO]: 1452114071869 Scheduling 10 seconds from now
xeoncraft: [16:01:21 INFO]: Sentury Working
xeoncraft: [16:01:21 INFO]: Sentury Running @ 1452114081871
xeoncraft: [16:01:21 INFO]: 1452114081872 TASK Sentury Running
xeoncraft: [16:01:21 INFO]: *\* [Saving] Rewards.bin
xeoncraft: [16:01:21 INFO]: *\* [Saving] Rewards.bin - SAVED
xeoncraft: [16:01:21 INFO]: *\* [Saving] Users.bin
xeoncraft: [16:01:21 INFO]: *\* [Saving] Users.bin - SAVED
xeoncraft: [16:01:21 INFO]: 1452114081882 Scheduling 10 seconds from now
xeoncraft: [16:01:31 INFO]: Sentury Working
xeoncraft: [16:01:31 INFO]: Sentury Running @ 1452114091885
xeoncraft: [16:01:31 INFO]: 1452114091885 TASK Sentury Running
xeoncraft: [16:01:31 INFO]: *\* [Saving] Rewards.bin
xeoncraft: [16:01:31 INFO]: *\* [Saving] Rewards.bin - SAVED
xeoncraft: [16:01:31 INFO]: *\* [Saving] Users.bin
xeoncraft: [16:01:31 INFO]: *\* [Saving] Users.bin - SAVED
xeoncraft: [16:01:31 INFO]: 1452114091903 Scheduling 10 seconds from now
xeoncraft: [16:01:41 INFO]: Sentury Working
xeoncraft: [16:01:41 INFO]: Sentury Running @ 1452114101907
xeoncraft: [16:01:41 INFO]: 1452114101908 TASK Sentury Running
xeoncraft: [16:01:41 INFO]: *\* [Saving] Rewards.bin
xeoncraft: [16:01:41 INFO]: *\* [Saving] Rewards.bin - SAVED
xeoncraft: [16:01:41 INFO]: *\* [Saving] Users.bin
xeoncraft: [16:01:41 INFO]: *\* [Saving] Users.bin - SAVED
xeoncraft: [16:01:41 INFO]: 1452114101917 Scheduling 10 seconds from now

**Comment by tlaundal** [comment]
This is not Houston or Houston java after my knowledge. What plugins do you have installed?

**Comment by ghost** [comment]
Plugins (21): GroupManager, Houston, Votifier2, WorldEdit, Vault, Multiverse-Core, GriefPrevention, Questioner, HolographicDisplays, WorldGuard, Essentials, PlotSquared, Autorank, EssentialsProtect, Towny, EssentialsSpawn, Multiverse-Portals, Multiverse-Inventories, EssentialsChat, EssentialsAntiBuild, uSkyBlock

**Comment by tlaundal** [comment]
Not a Houston problem. You'd have to test and find out what plugin it could be.
