### ISSUE TITLE
Server details not saving

### ISSUE THREAD

**Issue by Xelo** [SpaceCP/Bugs#13]
Hi,

as I mentioned on you forums: [Here](https://forums.spacecp.net/topic/292/can-increase-ram-over-2048mb/2)

I am not able to give any of my server more then 2048mb RAM (see the Xmx value)

```
minecra+ 15161  0.1  0.0  26004  1684 ?        Ss   10:41   0:00 SCREEN nodejs houston start
minecra+ 15163  0.0  0.1 670584 17128 pts/2    Ssl+ 10:41   0:00  \_ nodejs houston start
minecra+ 15165  3.4  0.5 1043056 88912 pts/2   Sl+  10:41   0:05      \_ /usr/bin/nodejs /home/minecraft/SpaceCP/houston.js --max-old-space-size=40
minecra+ 15210 11.5  1.8 5044888 311816 ?      Ssl  10:41   0:18          \_ java -Xmx2048m -Djline.terminal=jline.UnsupportedTerminal -jar minecraft_server.15w47c.jar nogui
minecra+ 15913  254  3.1 4934968 536632 ?      Ssl  10:44   0:25          \_ java -Xmx2048m -Djline.terminal=jline.UnsupportedTerminal -jar FTBServer-1.7.10-1490.jar nogui
```

One of my Server is set to 4096mb and the other to 1024mb. Both are always starting with 2048mb.
![SpaceCP Server Config modpack](http://i.imgur.com/Nn3t79M.png)
![SpaceCP Server Config vanilla](http://i.imgur.com/93alK2x.png)

I already reinstalled the node. No change.

**Comment by JamyDev** [comment]
This is an issue where the server details are not being reflected on the daemon.

**Comment by JamyDev** [comment]
Thanks for the report, the fix will be deployed in the next update.
