### ISSUE TITLE
SpaceCP Hanging on "wait while we setup your Server"

### ISSUE THREAD

**Issue by Rustypredator** [SpaceCP/Bugs#130]
Followup issue of #128 
The webinterface is hanging on "wait while we setup your server".
The Deamon is setup and connects properly, no error messages in the deamon log.
System is freshly setup debian 8.2

**Comment by Rustypredator** [comment]
Looks like it magically works now... thanks for your help ;)

**Comment by tlaundal** [comment]
Good it works now. Please report this if you experience it again.
