### ISSUE TITLE
Bungee cord support

### ISSUE THREAD

**Issue by faneQ123** [SpaceCP/Bugs#131]
Title says it all :dart:

**Comment by tlaundal** [comment]
This is planned, but we are waiting till everything Vanilla and Spigot is stable. 

Keeping the issue open for tracking, though.

**Comment by tips48** [comment]
https://forums.spacecp.net/topic/134/native-bungeecord-intigration/8

More info here

**Comment by faneQ123** [comment]
I knew about that post. This is just and update so they won't forget.
If you are here and you want to help. My houston stops by itslef on Linux 64 bit Turnkey. Any suggestions?
