### ISSUE TITLE
Whitelist Issue

### ISSUE THREAD

**Issue by ryan77627** [SpaceCP/Bugs#134]
I try to add people to the whitelist then the whitelist command errors out and when i reboot it doesn't contain anything. If I use /whitelist add [User] It works and displays on the panel and stays.

**Comment by ryan77627** [comment]
Found the issue. The in-game command works fine to add to whitelist and the whitelist checkbox under the users online section of the panel works. What doesn't is when you go to whitelists and type in a username. What happens is it only adds the uuid in quotes when in reality it needs uuid followed by a comma out of quotes then under it the same format only with username and no comma. Refer to the picture attached.
![converted_file_baff19fe](https://cloud.githubusercontent.com/assets/16727971/12370569/a8e3065a-bbe3-11e5-911b-e244d1e64ed0.png)

**Comment by totokaka** [comment]
Thanp, @ryan

**Comment by tlaundal** [comment]
Hi @ryan77627, thanks for reporting this issue.

You are missing a lot of necessary information in this issue. Please have a look here https://github.com/SpaceCP/Bugs#what-should-i-include-in-my-report

You say that it "errors out", I'm going to need to see that error.

I also tried reproducing this error, but was unable to do so in either Spigot/Bukkit or Vanilla Minecraft.

**Comment by ryan77627** [comment]
OK,

Browser: Mozilla Firefox on Fedora 23 x86_64
OS of Daemon: Lubuntu i686
Error on Minecraft Spigot Latest on getspigot.org
Area of panel, Users;Whitelist and Bans
Web Error AFTER TRYING TO ADD USER UNDER WHITELIST!!

```
Error: [object Object]
n</c.prototype.do/<@https://app.spacecp.net/js/spacecp.js?build=ce9a253:649:16274
e.exports</c.request/</<@https://app.spacecp.net/js/spacecp.js?build=ce9a253:646:22382
kf/this.$get</m.prototype.$eval@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:132:354
kf/this.$get</m.prototype.$apply@https://ajax.googleapis.com/ajax/libs/angularjs/1.4.5/angular.min.js:133:47
e.exports</e.$safeApply@https://app.spacecp.net/js/spacecp.js?build=ce9a253:663:17520
e.exports</c.request/<@https://app.spacecp.net/js/spacecp.js?build=ce9a253:646:22355
n@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:3897
n.prototype.emit@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:4831
n.prototype.onPacket@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:20132
r.prototype.onPacket@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:16531
n.prototype.onPacket@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:10542
n.prototype.onData@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:10286
r.prototype.open/this.websocket.onmessage@https://app.spacecp.net/js/spacecp.js?build=ce9a253:648:21135
```

And after server reboot (not daemon just server in daemon) it works again but doesn't show the person I added to whitelist unless I change the whitelist file, see above.

Finally it works on the server I've had for a bit but still latest, but i made this server yesterday and doesn't wanna work.

**Comment by ryan77627** [comment]
Oh and taking a look at the log files of the minecraft server after trying to add a whitelisted play I saw:

```
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:176) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedPlayerList. <init> (SourceFile:30) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedPlayerList.C(SourceFile:123) [spigot_server.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.JsonList.load(JsonList.java:195) ~[spigot_server.jar:git-Spigot-db6de12-18fbb24]
java.lang.NullPointerException
[11:12:31] [Server thread/WARN] : Failed to load white-list: 
```

FYI its upside down read from bottom to top.

**Comment by tlaundal** [comment]
Thanks for the info and error messages. We'll look into it.

**Comment by tlaundal** [comment]
I believe this is an issue at your end.

First ensure that you are in fact running the latest daemon version. Please redownload the zip file from the daemon setup guides.

If this is the case and it still doesn't work, please check that the server is set up as a bukkit server in the panel. You do this by checking the server settings. I also need to know in what context the java error appears. Is it when the server starts, stops, or when you try to add a player?
Finally i need to know exactly what you entered in the whitelist field.
It would also help enormously if you could do a restart of the server, try to add a player, and then stop the server again, and finally give me the full log for this server run. If you want, you can send this as a PM.

**Comment by 2SnHamans** [comment]
I am having a similar issue. Players that have previously been added to the whitelist are not showing up in the control panel - they are still in the whitelisted file, however.
