### ISSUE TITLE
McSignOnDoor

### ISSUE THREAD

**Issue by CaptnSisko** [SpaceCP/Bugs#138]
McSIgnOnDoor will sometimes prevent servers from starting on certain ports.

How to reproduce the problem:
1) Create a minecraft server (I was using spigot, vanilla should work too)
2) Enable McSignOnDoor
3) Shut down the server
4) Delete the server, but keep the deamon running
5) Try to make another server on the same port. You will receive the "failed to bind port" error because it is being used by McSignOnDoor. Pinging the server from minecraft will show the McSignOnDoor MOTD and disconnect message.

**Comment by tlaundal** [comment]
Thanks for the report!

I have fixed this now, and it will be deployed with the next build.

(Fastest issue fix yet, I think).
