### ISSUE TITLE
[PANEL] Can't assign more then 10gb ram

### ISSUE THREAD

**Issue by MiniDigger** [SpaceCP/Bugs#14]
I think the list with ram options should expand when selecting 10gb

**Comment by jithatsonei** [comment]
I would put this in the feature request section as it _SHOULDN'T_ be a bug

**Comment by MiniDigger** [comment]
see https://forums.spacecp.net/topic/272/higher-amounts-of-memory/2

**Comment by Antariano** [comment]
Fixed in build 6
