### ISSUE TITLE
kCauldron is not recognized as a Bukkit server

### ISSUE THREAD

**Issue by tenten8401** [SpaceCP/Bugs#143]
As the title says, it just wont go away
http://tentencraft.net/pic/747478f0-788d-4e81-b60b-56efd7eeec8e

**Comment by tenten8401** [comment]
May i also mention, Here is the AJAX request:
![AJAX Request](http://tentencraft.net/pic/d/e7ea2867-0829-40bf-a8d9-8db9af063439.png)

**Comment by napei** [comment]
I second this...
My KCauldron installation on Linux just started to do this and I can't do anything but start, stop, kill and restart the server >.>

**Comment by tlaundal** [comment]
@tenten8401 What server mod are you using?

I need the server output from when the server is starting to determine why SpaceCP thinks it's a Vanilla server.

**Comment by tenten8401** [comment]
kCauldron

**Comment by tlaundal** [comment]
Ok. A fix for kCauldron not being recognized as a Bukkit server is coming up in the next build.

In addition we need to fix the "Keep using .." button, so it actually works, see #80 for that.
