### ISSUE TITLE
formatting from MOTD on Dashboard and Banner not showing

### ISSUE THREAD

**Issue by HexaCubist** [SpaceCP/Bugs#144]
In Minecraft MOTD's you can apply formatting and unicode characters to make it look nicer:
![image](https://cloud.githubusercontent.com/assets/8563277/12834862/fb00fdfc-cc0f-11e5-98c9-71305499e11c.png)

However when on the dashboard, Spacecp does not know how to interpret this data and so it leaves the formatting symbols in, and can't handle special characters such as seen in the image above. The result is below:

![image](https://cloud.githubusercontent.com/assets/8563277/12834891/22f5457a-cc10-11e5-9194-4f800457afcd.png)

![image](https://cloud.githubusercontent.com/assets/8563277/12834896/29538a80-cc10-11e5-8fa6-1d3b1036a65e.png)

**Comment by tlaundal** [comment]
Thanks for the report, but this is already tracked in #119. 

Closing as a dupe.
