### ISSUE TITLE
SpaceCP not detecting Dameon

### ISSUE THREAD

**Issue by Jackzmc** [SpaceCP/Bugs#145]
Browser: Latest Chrome
OS: Windows 10 Home

I wanted to try this thing out and I went and created a folder on my desktop and installed the dameon, and spaceCP detected it completely fine, but when I went to start it, it won't detect it no matter what. I tried portforwarding the port too incase.
It is saying it has contacted SpaceCP, but doesn't look like it.
Log file:
[houston.2016-2-5.txt](https://github.com/SpaceCP/Bugs/files/119122/houston.2016-2-5.txt)

**Comment by JamyDev** [comment]
There's 2 parts of the connection to SpaceCP, the daemon being able to see SpaceCP is just to check if you have an outgoing connection to the internet. 

There's the second part of the connection where SpaceCP tries to find your daemon, it seems like that is failing for you.

Looking at the log it seems like you have Houston on port 35566, try this tool with port 35566 to test if incoming connections to that port are allowed: http://www.yougetsignal.com/tools/open-ports/ (Make sure Houston is running)

If this fails it's a firewall issue, sure you put in the right port etc.

**Comment by Jackzmc** [comment]
When I tried starting up server, It got stuck on updating and disabling my firewall allowed it in, and the tool says Port is Opened.

The SpaceCP Dameon Setup page is stuck connecting through and says connection error  (Firewall still disabled)

**Comment by JamyDev** [comment]
Can you refresh the page and see if it's resolved? Also can you double check you provided the correct IP in the daemon configuration?

**Comment by Jackzmc** [comment]
I have been refreshing every so often, and now it just instantly says Conn error (The server is still up)

I didn't know what IP to enter, so I put my broadcast/router ip [The one when you type 'what is my ip' on google]. I'm probably doing something dumb somehow so

**Comment by xiaopeare** [comment]
I have the exact same issue, I've even pinged it, and it loads, but SpaceCP itself doesn't detect it.

**Comment by tlaundal** [comment]
@JackzTaEpic @thiotone Are you still experiencing this issue with the latest daemon version?

**Comment by Jackzmc** [comment]
I haven't done anything about it, I'll redownload it and try it

_Jackz_
Server Website http://jackzcraft.net | Twitter
http://twitter.com/jackzminecraft | JackzCraft Support Email
support@jackzcraft.com

**Comment by Jackzmc** [comment]
Okay final update. I think the same issue is happening. It is failing to connect. It was setup fine, and it said successfully called back to scapeCP but it still hasn't detected it. I tried disabling firewall too.

Could it be anything related to windows?

**Comment by tlaundal** [comment]
Here are som quick troubleshooting steps, assuming you are using the default port.
1. Open [https://localhost:35566/ping](https://localhost:35566/ping) (notice the **`s`**) from the machine running the daemon. You will get an ssl error, but just bypass it. You should see the text `Pong!`. This verifies that the daemon is running, and listening on the correct port.
2. Go to another computer on your local network and go to `https://<local ip of server>:35566/ping`, where `<local if of server>` is the LAN IP-address of the machine running the daemon. If you don't know how to find this, google it. The result should be the same as in the previous step. This verifies that it is not a firewall on your server machine that stops the daemon's connection.
3. With a computer that is on another network, go to `https://<remote ip of server>:35566/ping`, where `<remote ip of server>` is the IP-address that [ipecho.net](http://ipecho.net) reports from the server machine. The result should be the same as in the other steps. This verifies that the daemon is visible from the internet.

Post what you get from each step.

**Comment by Jackzmc** [comment]
The localhost on step one is not loading. The daemn is running when I try to start it, I tried to stop it (node houston stop) and forcestop (node forcestop, and node houston forcestop)

**Comment by tlaundal** [comment]
So you are not able to start the daemon to begin with?
If it says it is already running, go into Window task manager and kill all processes named `node` or `java` (This might close other programs you have open, so close everything except your browser first), then try again.

**Comment by Jackzmc** [comment]
I tried closing it and it restarted and closed prompt. I'll do that when I
get back home in an hour or so

On Sunday, March 27, 2016, Tobias notifications@github.com wrote:

> So you are not able to start the daemon to begin with?
> If it says it is already running, go into Window task manager and kill all
> processes named node or java (This might close other programs you have
> open, so close everything except your browser first), then try again.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/SpaceCP/Bugs/issues/145#issuecomment-202088925

## 

_Jackz_
Server Website http://jackzcraft.net | Twitter
http://twitter.com/jackzminecraft | JackzCraft Support Email
support@jackzcraft.com

**Comment by Jackzmc** [comment]
I don't see any "node" or "java" proccess, detail, or service. It still says its running when I do node houston start

**Comment by xiaopeare** [comment]
Ok, like I've said, I've pinged my server, and it works. SpaceCP can detect that my daemon has been installed. However, when I start the daemon, SpaceCP doesn't detect it. I also reinstalled a couple times. I've even port forwarded it.

EDIT: I see the node and java processes.

**Comment by Jackzmc** [comment]
I had that issue too @thiotone but now I can't do the troubleshooting above because the daemon is running (and I can't stop it)

**Comment by tlaundal** [comment]
@JackzTaEpic Please delete the file `houston.pid` in the root of your daemon installation, this is what prevents the daemon from starting, I think.

@thiotone Please follow the steps I described [above](https://github.com/SpaceCP/Bugs/issues/145#issuecomment-202067956), so I can get an accurate picture of where the problem is. SpaceCP can detect that your server is installed because that doesn't require a connection established _to_ the daemon, only from it to SpaceCP.

**Comment by xiaopeare** [comment]
Oh, I fixed it, my problem was that the IP I entered in SpaceCP was a local IP, I thought that was what my computer's IP was. I just put in my public IP, and port forwarded that, then SpaceCP was able to connect to it.

**Comment by Jackzmc** [comment]
Yep that worked. I got it connected, and portforwarded. I think this issue would be fixed then
