### ISSUE TITLE
File Error

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#146]
When I make a server, Houston spits out an uncaught exception error: http://imgur.com/d8BGI7V

Details
Windows 10 10586.72
Houston build: 245
Latest Chrome Beta
Java 1.8_66

**Comment by JamyDev** [comment]
You're running a dev build of Houston. We cannot support these until we release them. Please revert back to 204 and try again.

**Comment by SAIYAN48** [comment]
Isn't 204 dev? In the latest changelog, Luca linked build 203 in the post: https://forums.spacecp.net/topic/367/open-beta-build-8-lightning-round

**Comment by JamyDev** [comment]
You are correct, sir. 203 it is! Apologies.

**Comment by SAIYAN48** [comment]
I'm good at noticing details :stuck_out_tongue:

**Comment by JamyDev** [comment]
I'm good at being tired.

**Comment by SAIYAN48** [comment]
How long should setup for a server take? Right now, the panel says "Please wait while we set up your server...", but the daemon output remains the same.

**Comment by SAIYAN48** [comment]
Now the Daemon is connected, but the server isn't.
