### ISSUE TITLE
Logs messed up

### ISSUE THREAD

**Issue by 35grain** [SpaceCP/Bugs#148]
When viewing the logs tab and scrolling down on the panel the output doesn't really seem to be in order.

![image](https://cloud.githubusercontent.com/assets/7030797/13006892/ca62f986-d194-11e5-9cb7-0af46764d340.png)

**Browsing on Google Chrome 48.0.2564.109 m
Daemon running on Ubuntu-15.04-x86_64
Apart from failing to load the banner (which is also an issue - Failed to load resource: the server responded with a status of 500 (Internal Server Error)), no errors produced.**

**Comment by tlaundal** [comment]
Please include all required information: 
https://github.com/SpaceCP/Bugs/blob/master/README.md

**Comment by 35grain** [comment]
^

**Comment by tlaundal** [comment]
Hmm. What houston / daemon version? What Minecraft distribution?

**Comment by 35grain** [comment]
Houston version: d6874b781ffdffed00dfe93d10bcc65e0eecd351_1452185246_203
Minecrafts' build & version: 14545960 16w05b

I doubt it's an issue with the daemon though.
