### ISSUE TITLE
SpaceCP not detecting daemon

### ISSUE THREAD

**Issue by napei** [SpaceCP/Bugs#151]
The daemon starts and says it has "called back to SpaceCP and starts the server. However, the CP will not detect the daemon as running.
The port is open, has been checked properly.
When reinstalling through npm on the reinstall page on the CP the CP detects that the daemon has been set up, but will not detect that it has been started, even after multiple reinstalls.
port 35566 is forwarded to the correct server on my network.
had that issue before when another server had the wrong port (I'm good at being tired)
Startup log:

> info: [bootstrap] Checking module existence...
> info: [bootstrap] Module check completed.
> info: Starting Houston (Build: 249)
> info: info: [wrapper] Checking for updates...
> info: info: [wrapper] Houston is up to date!
> info: Checking Houston integrity...
> info: Integrity check complete!
> info: Checking dependencies for houston_game_minecraft
> info: Checking dependencies for houston_mod_bukkit
> info: Starting internal WebSocket server listening on 35565...
> info: Starting remote WebSocket server listening on 35566...
> info: Calling back to SpaceCP...
> info: WebSocket manager running!
> info: [upload] Uploads manager activated.
> info: Houston start completed.
> info: pn-hub: Loading as Bukkit Minecraft server
> info: [network] Successfully called back to SpaceCP

**Comment by SAIYAN48** [comment]
Similar to #145 and #145 @JamyDev

**Comment by JamyDev** [comment]
Again have a look, do you have access to `https://<external-ip>:35566/ping` When the daemon is running? If so, send me a PM on https://forums.spacecp.net

**Comment by napei** [comment]
PM sent, however issue resolved itself

**Comment by SAIYAN48** [comment]
Solved itself for me too.

**Comment by tlaundal** [comment]
Closing. See #145 for status.
