### ISSUE TITLE
Not Able To Change Password

### ISSUE THREAD

**Issue by wolfiepawz** [SpaceCP/Bugs#156]
Hi.

Trying to go into Settings and change my password, but it doesn't work.
I press "Save" but nothing happens - It does not change the password.

**Comment by Forge-Media** [comment]
Not sure if related but I can simply not login at all. I've reset my password via email correctly, but with correct user details I get the following: https://i.imgur.com/41QBgce.png result and with incorrect user details I get this: https://i.imgur.com/OlbxOi7.png

More details: http://i.imgur.com/8isqObw.png

My account name is: Jeremy Paton & has 1 minecraft server (Spigot)

**Comment by Antariano** [comment]
Taking a looksie now

**Comment by Antariano** [comment]
I fixed the original issue in the next build. 
@Forge-Media, in your screenshot when you enter the correct password, could you expand the ![](http://i.antariano.com/2016-02-19_16-08-13DgmBMsMc4mvgyShnmUNpoDSCoD9lMjnSrc2Bim19.png) object returned by the API by clicking the little arrow? I'm particulary interested in the `data` property

**Comment by Forge-Media** [comment]
More details: http://i.imgur.com/8isqObw.png (think this one shows what your looking for)

**Comment by Antariano** [comment]
No, I need you to expand the Arrow next to the "object" text :) like my screenshot shows

**Comment by Forge-Media** [comment]
Sorry did not read your question properly :(

http://i.imgur.com/xx3TyIw.png here you go.

Odd error as I definately did activate my account and have been accessing it at least twice to four times a month

**Comment by Antariano** [comment]
That helps, thanks! Going to get it fixed and the appropriate people slapped :)

**Comment by Forge-Media** [comment]
fixed it the link in the activation email in Gmail is not clickable.

and obviously i thought I had activated the account. also the link on the button (which is not clickable) can't simply be copied into the browser.

I had to copy the link from the email and figure out the correct way to past it into the app, which was this: https://app.spacecp.net/#/auth/confirm?username=shadowrider921009&token=9d16bb4494b37377f15a420907fdd338e493ef764cb54ab8******************

See this image: http://i.imgur.com/duYtVpB.png

**Comment by Antariano** [comment]
Uh oh... Awesome catch! Fixing now
