### ISSUE TITLE
[Panel/Daemon] Chat Error

### ISSUE THREAD

**Issue by jonyroda97** [SpaceCP/Bugs#16]
http://pastebin.com/zfFqjR1j

https://gyazo.com/cd0ae447caf6a5ce2b6bf6a9234bec3a

**Comment by MiniDigger** [comment]
the first error is caused by your inoffical essentials version
the duplicated messages were fixed in build 4, shou should update houston

**Comment by JamyDev** [comment]
Going to close this, let me know if the double messages are still there.
