### ISSUE TITLE
Edit Server title

### ISSUE THREAD

**Issue by 35grain** [SpaceCP/Bugs#163]
"Edit Server:  _server name_" isn't being displayed properly
**What it looks like:**
![image](https://cloud.githubusercontent.com/assets/7030797/13259256/49ec58e6-da5f-11e5-9a14-f18ca9ddcb20.png)
**What it probably should look like (+/- pxs):**
![image](https://cloud.githubusercontent.com/assets/7030797/13259307/751b635e-da5f-11e5-8ada-7a7f332c5a61.png)
**Browsing on Google Chrome 48.0.2564.116 m**

**Comment by Antariano** [comment]
Hey, what resolution are you running?

**Comment by 35grain** [comment]
Chrome's telling me 1366 x 643 (that's in normal view mode). The issue seems to solve itself once in fullscreen mode (1366 x 768). Otherwise resizing it doesn't make a difference (scaling down). I have also cleared my cache so it can't be the cause of those dark magic witches.

**Comment by 35grain** [comment]
While the cards issue (#164) seems to be solved as of now, then did this & #174 get deployed as well? Since currently, for me anyway, it doesn't seem so.

**Comment by jamesbirtles** [comment]
They didn't actually get deployed, they were sat in a pr that we forgot to merge. Will be fixed on next deploy :smile:

**Comment by 35grain** [comment]
Ah, gotcha! (:
