### ISSUE TITLE
HoustonBukkit NoSuchMethodError in Spigot 1.9

### ISSUE THREAD

**Issue by Willsr71** [SpaceCP/Bugs#166]
In the 1.9 build of Spigot there is a NoSuchMethodError from HoustonBukkit that constantly spams the console.
![console](https://i.gyazo.com/d2a1e0e4670404f3835d6cedb84c8c9b.png)

I decompiled the plugin to see if it was just an outdated api issue, but it appeared to not be there in the first place. This is probably just a decompile error, but have a screenshot anyway. Screenshot 1 is the decompiled source, screenshot 2 is the fixed source with the offender highlighted.
![decompiled source](https://i.gyazo.com/cf99beac1a399a0b275b5d918ff9ce82.png)
![fixed source](https://i.gyazo.com/c53e04e3818e81dbb1dd4a5ca6958179.png)

I did test the plugin again with Spigot 1.8 and it worked flawlessly, which completely refutes the disappearing method above...
- Reproduction: Grab the version of spigot I was using (https://jenkins.willsr71.net/job/BuildTools/12/artifact/spigot-1.9.jar) for your server jar and start the server.
- Browser: Chrome Canary 51.0.2662.0
- Daemon OS: Windows Server 2012 R2
- Game: Minecraft, Mod: Bukkit/Spigot

**Comment by JamyDev** [comment]
Thanks for the detailed report, I'll fix it up now!

**Comment by JamyDev** [comment]
As you can read under the `CraftBukkit` tag [here](https://www.spigotmc.org/threads/minecraft-1-9-release.127186/), they removed that method.

**Comment by JamyDev** [comment]
An updated dev build has been made, give it a try! https://dl.spacecp.net/houston/houston_250_1456939237.zip

**Comment by Willsr71** [comment]
Yep that fixed it. Thanks! As for #167 make sure you deleted houstonbukkit.jar from the plugins folder before starting the server.

**Comment by JamyDev** [comment]
Ah, it should be overwriting it actually, so that's a bug. I'm assuming you're on widows?

**Comment by Willsr71** [comment]
Yep

**Comment by Willsr71** [comment]
Closed because the issue reported has technically been fixed.

**Comment by Willsr71** [comment]
Fixed in dev versions. Not releases apparently though. #180

**Comment by JamyDev** [comment]
Yeah release for that going out tomorrow

**Comment by Willsr71** [comment]
More interesting things to look forward to. Awesome.

**Comment by JamyDev** [comment]
Released latest Houston.
