### ISSUE TITLE
[PANEL] Settings entry server.jar not showing server jar

### ISSUE THREAD

**Issue by tobiasnagel** [SpaceCP/Bugs#17]
The Server.jar entry in settings doesn't show the server jar
OS: Windows Server 2012
Server: Spigot 1.8.8
Houston: Build 157
![jar](https://cloud.githubusercontent.com/assets/9637659/11763741/4ea47bca-a116-11e5-93ee-a5e7555bda0d.png)

**Comment by tobiasnagel** [comment]
so, after some page reloads / server restarts / deamon restarts, it is working again

**Comment by Antariano** [comment]
Is this still happening?

**Comment by tobiasnagel** [comment]
no, it shows again

**Comment by Antariano** [comment]
Ok thanks!
