### ISSUE TITLE
Banners broken once again?

### ISSUE THREAD

**Issue by 35grain** [SpaceCP/Bugs#179]
After some fixes were deployed, it seems like they might have messed up something with the banners again.
![image](https://cloud.githubusercontent.com/assets/7030797/13885674/2c8273e0-ed3c-11e5-84f6-c6b0bd01b450.png)
`{"status":500,"error":"Error generating banner."}`
https://app.spacecp.net/api/v2/servers/56bcb5a062ad4b2e0d04e80c/banner?.png

**Comment by JamyDev** [comment]
I probably forgot to install the image manipulation tool on one of the servers, whoops :sweat_smile:

**Comment by JamyDev** [comment]
I'll do it once I get home, thanks for the report

**Comment by 35grain** [comment]
No problem! ^-^

**Comment by JamyDev** [comment]
Fixed.
