### ISSUE TITLE
players info box shows incorrect information

### ISSUE THREAD

**Issue by tobiasnagel** [SpaceCP/Bugs#18]
The players info is showing incorrect information. it says 2/20 although there si nobody on the server. also the OP's avatars are not shown correctly
OS: Windows Server 2012
Server: Spigot 1.8.8
Houston: Build 157
![players](https://cloud.githubusercontent.com/assets/9637659/11763745/b401097a-a116-11e5-95b3-3731aa2a54bd.png)

**Comment by JamyDev** [comment]
Closed, since #28 was fixed.
