### ISSUE TITLE
Bootstrap Error?

### ISSUE THREAD

**Issue by braylandon92** [SpaceCP/Bugs#182]
So Im getting something along the lines of 
info: [bootstrap] Checking module existence...
info: [bootstrap] Module check completed.
info: Starting Houston (Build: 249)
info: info: [wrapper] Checking for updates...
info: info: [wrapper] Houston is up to date!
info: Checking Houston integrity...
Houston needs to be bootstrapped first. (Missing files/folders: servers/, config
/, config/houston.json, config/server.key, config/server.cert, config/servers)
info: Houston exiting.
info: [wrapper] Daemon crashed in an unrecoverable way. Not restarting
info: [wrapper] Please look at the error above and take appropriate action

I do not know what to do. It seemed to install fine. I tried again and same thing. PLEASE HELP. Thanks.
This is on linux.

**Comment by JamyDev** [comment]
My first guess is you're using powershell?

Please don't use powershell :sweat_smile:

**Comment by JamyDev** [comment]
And I was too fast.. seems like the `node houston bootstrap` part of the command didn't run. (It's the part before the 2 &&'s in the line you have to paste into the console)

**Comment by braylandon92** [comment]
So how do I fix that? Shall I run it again?

**Comment by JamyDev** [comment]
You could try that.

**Comment by braylandon92** [comment]
Okay. Let me make sure the command was typed correctly as well.

**Comment by braylandon92** [comment]
Off to the server room! Ugh.

**Comment by braylandon92** [comment]
Okay. So rerunning the command worked! Thanks.
