### ISSUE TITLE
Improper Paper Support

### ISSUE THREAD

**Issue by OutdatedVersion** [SpaceCP/Bugs#183]
It seems that SpaceCP doesn't properly support the '[Paper](https://aquifermc.org/)' distribution of Spigot. It is indeed fully compatible with the Bukkit & Spigot API, so no worries for the Houston plugin. While attempting to use the Spigot/Bukkit jar option presented by the control panel it will consistently inform me that I am running vanilla MC, and not Paper. Then I must [change](https://gyazo.com/cfdc85bc5345f6ebd609ed36c37c8e7a) my mod type on SpaceCP to continue using it. Thoughts?

**Comment by tlaundal** [comment]
I've fixed this in the code now. It will be included in the next release of the daemon.
