### ISSUE TITLE
Stuck at 3 players?

### ISSUE THREAD

**Issue by Colinstech** [SpaceCP/Bugs#186]
![image](https://cloud.githubusercontent.com/assets/16324329/14057333/8180bfee-f2ca-11e5-97dd-d68fc769d5db.png)

it starts with this, then as players come online it counts up. so 1 player means 4 on the cp. 2 players 5 on cp and so on.

**Comment by tlaundal** [comment]
Do you have the same problem after restarting
1. The server in SpaceCP
2. The daemon running the server

?

**Comment by Colinstech** [comment]
yes.

**Comment by tlaundal** [comment]
Is this a vanilla, bukkit/spigot or modded server? 
Could you also check if you have the same problem if you try a new installation of the daemon?

**Comment by Colinstech** [comment]
its bukkit server. i tried it on different computer and reinstalling. still had the problem

**Comment by Colinstech** [comment]
updated daemon to houston_265_1459654558.zip  from houston_254_1459084548.zip and the problem is fixed.

along with all the crud the console was giving out.

**Comment by JamyDev** [comment]
Awesome!
