### ISSUE TITLE
Cannot change SpaceCP password; 2FA suddenly stops working, cannot sign in.

### ISSUE THREAD

**Issue by skylordjason** [SpaceCP/Bugs#188]
I've been using 2FA for some time now on SpaceCP, and I enjoy the ability to do so.

Out of habit, I change my passwords once every 3 months. When attempting to change my SpaceCP password, I got no response. I shrugged it of as a bug, but now when I attempt to sign in I get the 2FA popup and I get no response when typing in the authentication code.

**Comment by JamyDev** [comment]
Hmm, does a recovery code work?

**Comment by skylordjason** [comment]
Unfortunately no. It seems to not know what to do after putting in either. It acts like it's loading something and then shows the 2FA modal again.

**Comment by skylordjason** [comment]
Well I tried 2FA again and it suddenly worked. I still get no response when changing my password however. All I get is a blank toast notification.

![No Response to Changing Password](https://i.gyazo.com/445a387532e4f127822d97135adfd31c.gif)

Logging out and logging back in still requires the old password.

**Comment by JamyDev** [comment]
So the 2FA thing was caused due to our time not being synced correctly, sorry about that. I'll look into the password changing now.

**Comment by JamyDev** [comment]
The empty message could mean that your new password doesn't follow the requirements. Best way to find out is to open your browser console (F12 probably) and checking out the latest message's error object:

![](https://i.jamy.be/95rqy0v3tk4hl3o.png)

**Comment by skylordjason** [comment]
I get this response. My old password contains an '@' symbol.

![image](https://cloud.githubusercontent.com/assets/8324596/14230970/5a129d80-f935-11e5-97ea-95fc4bcceb10.png)

**Comment by JamyDev** [comment]
Ah, that's definitely not right. Will be fixing that shortly!

**Comment by JamyDev** [comment]
Should be fixed! Let me know how it goes!

**Comment by skylordjason** [comment]
Works perfectly, thanks!
