### ISSUE TITLE
BungeeCord EULA issue

### ISSUE THREAD

**Issue by alexbegt** [SpaceCP/Bugs#199]
**Specific steps to reproduce the issue**
- Open to your panel, and go to Administrate under a bungee server
- It will pop up telling you to accept the Mojang EULA
- Clicking the button will not do anything, but return red text saying: "Method 'acceptEULA' not found".

**Operating system of your daemon**
- Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)

**What game and mod the issue occurred on**
- Game: Minecraft
- Mod: BungeeCord

**What area of the panel the issue occurred on**
- The Administrative Panel for A Bungee Server

**Was there any code or error displayed? (F12 in chrome and click on the red X's on the near-bottom right if its there and include those errors)**
- There is no error diplayed in the console but red text saying "Method 'acceptEULA' not found." comes up.

**Daemon version**
- 265

**Node Version**
- version 5.10.1

*_Browser *_
- Chrome version 50.0.2661.87 

Picture of log from F12

http://i.imgur.com/4orylcP.png

Picture of Page:

http://i.imgur.com/EY7tINM.png

**Comment by JamyDev** [comment]
Hey, could you please complete your issue report with the following details: [Guidelines](https://github.com/SpaceCP/Bugs#what-should-i-include-in-my-report)

**Comment by alexbegt** [comment]
Do you want a new Issue report created?

**Comment by JamyDev** [comment]
Nope just click the edit pencil in the top right.

**Comment by alexbegt** [comment]
Done, Updated.

**Comment by JamyDev** [comment]
Can you just provide the daemon version too please? :)

**Comment by alexbegt** [comment]
Just did :)

**Comment by alexbegt** [comment]
If you would like more information, just comment here and I'll update it :)

**Comment by alexbegt** [comment]
Anything new on this?

**Comment by alexbegt** [comment]
I guess this goes with #80 ?

**Comment by JamyDev** [comment]
It shouldn't, it's only when you choose "don't change that it will not update"

**Comment by alexbegt** [comment]
I've might've found one that does go with #80 , For a different server on my list, it says it detects bukkit but is set to bukkit. We run kcauldron on that different server.

**Comment by alexbegt** [comment]
This seems to have resolved it's self, Must have been a weird glitch!

**Comment by alexbegt** [comment]
It strikes again :/ http://i.imgur.com/rPfkW3P.png
