### ISSUE TITLE
IP ban pardon not working

### ISSUE THREAD

**Issue by jithatsonei** [SpaceCP/Bugs#20]
I am currently on Minecraft server snapchat 15w47c, houston build 157. And while banning a IP for testing works, when I attempt to pardon the IP it does nothing.

Developer console reveals that the pardon message was POSTED but returned with an error 500. With the message 'The IP is required'

Log:
POST: https://ghostbin.com/paste/9umu8
Return: https://ghostbin.com/paste/qpqk4

Currently on Chrome 47

**Comment by JamyDev** [comment]
The ip seems to not be set on pardon.

**Comment by Antariano** [comment]
This was fixed.
