### ISSUE TITLE
Extreme Panel Lag

### ISSUE THREAD

**Issue by philip-ulrich** [SpaceCP/Bugs#202]
## Expected Behavior

The control panel should be responsive.
## Current Behavior

The control panel becomes unresponsive if you leave the control panel open for hours (or if your console is spamming.. a few minutes)
## Steps to Reproduce (for bugs)
1. Login to panel
2. Open Server
3. Open Console
4. Spam a command that gives a long output 50x or so (or leave an active server open for a few hours)
5. ???
6. No Profit
## Context

I have a computer that I leave the console up on constantly. It makes me have to close out the browser window every couple hours and it lags my system
## Your Environment

Mac OS X El Capitan
MacBook Pro Retina (and Mac Mini)
Chrome, Safari, Webkit (inside Royal TS X)
- Daemon version used:
  [redacted@mc2 ~]$ node houston -v
  0.0.1
- Environment name and version (e.g. Chrome 39, node.js 5.4):
  [goldenapple@mc2 ~]$ node -v
  v5.10.1
  Safari 9.0.1
  Chrome 50
- Operating System and version (desktop or mobile):
  Mac OS X El Capitan
## Screenshots

http://d.l33t.tech/1ds74/1425f5AC
^ This is what happens whenever it freezes up. Not really sure if that is a needed screenshot though. :D

**Comment by tenten8401** [comment]
Glad to know I'm not the only one. Here are some website tests (using my session id so it's logged in) from websitetest.com... It really needs some cleanup and optimization.

http://www.websitetest.com/ui/tests/5727ac9b7454fc3cec000001

**Comment by tenten8401** [comment]
I think this is being deployed right now, just logged on and saw that it was no longer keeping every single line of console output, and it was a lot more responsive.

**Comment by tenten8401** [comment]
Yuess... 60 fps smooth. Thanks guys!
