### ISSUE TITLE
Can't /fml confirm

### ISSUE THREAD

**Issue by tenten8401** [SpaceCP/Bugs#206]
## Expected Behavior

I should be able to type fml confirm into the console
## Current Behavior

fml confirm doesn't do anything
## Steps to Reproduce (for bugs)

1. Go to SpaceCP
2. Get to a state where you need to type /fml confirm
3. Type fml confirm
4. Nothing
## Context

I can't start my server after removing specific blocks from mod configs. Please set the server to start with -Dfml.queryResult=confirm
## Your Environment

- Daemon version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
  Browser: Doesn't matter
  Operating System: Ubuntu 15.04 x64

**Comment by tenten8401** [comment]
Scratch that, the same solution for McMyAdmin works here, for anyone seeing this, type `//fml confirm` into console, and it will work.

**Comment by tlaundal** [comment]
The way I see this, it is not a problem with SpaceCP, but rather with FML. The `fml confirm` command should be passed to the console as any other command. We do not keep a list of allowed commands or anything like that.

The java argument, though, is something we should support. In the server settings it should be possible to define a set of custom java arguments, like `-D...` arguments and memory arguments, notably `-Xms`.

**Comment by JamyDev** [comment]
See the issue here is that `/fml confirm` is actually expecting to see the leading slash for some reason. For any other console command this is not needed and more often than not it will complain that it can't find the command if it has the leading `/`. For this reason we decided to automatically remove the first leading slash (just like MCMA, because users).

**Comment by tenten8401** [comment]
But it requires a double slash to actually work, even when removing the first slash automatically through SpaceCP.

**Comment by JamyDev** [comment]
Yeah because SpaceCP removes the first `/`

**Comment by tenten8401** [comment]
So technically 3 slashes are needed. What I'm saying is i need to type `//fml confirm`` into the console

**Comment by JamyDev** [comment]
Ehh Yup if that's what you want to achieve..
