### ISSUE TITLE
IllegalStateException when getting players with Spigot

### ISSUE THREAD

**Issue by Willsr71** [SpaceCP/Bugs#212]
When using Spigot 1.7/1.8 (and presumably everything below as the method was changed in 1.9), houstonbukkit throws an exception every time it tries to get the player count.
## Steps to Reproduce (for bugs)
1. Create a 1.7/1.8 spigot/bukkit server ([our jar](panel.preludecraft.com/stuff/spigot.jar))
2. Start said server
3. Watch the console
## Your Environment
- Daemon version used: 265
- Environment name and version: Node.js 4.3.2, Chrome 52.0.2724.0 canary
- Operating System and version: Windows Server 2012 R2
## Screenshots

![](https://i.gyazo.com/8684fe741c11062c3e63d08935a9b680.png)

**Comment by Willsr71** [comment]
On a side note, I am pretty sure that @JamyDev is going to soon regret his earlier decision about Prelude Network ;)

**Comment by JamyDev** [comment]
Lol no this is good, the more bugs we fix the better. This is one for @totokaka though ;)

**Comment by Willsr71** [comment]
Continuing with the side notes, I believe this may be a side effect of fixing #166.

**Comment by philip-ulrich** [comment]
Also exists in 1.9.2. See #215 for (closed) duplicate error.

**Comment by JamyDev** [comment]
Fix deployed!
