### ISSUE TITLE
Plugin access denied

### ISSUE THREAD

**Issue by Willsr71** [SpaceCP/Bugs#214]
When accessing the plugin section of a server, an error pops up that says "There was an error loading your plugins". Looking in the console there is a request along the lines of "getPlugins" and then a request immediately after that that has a status of 403 access denied along with a message of 403 access denied.
## Steps to Reproduce (for bugs)
1. Administer a server
2. Go the the plugins section of the server
3. See and believe
## Your Environment
- Daemon version used: 265
- Environment name and version: Node.js 4.3.2, Chrome 52.0.2724.0 canary
- Operating System and version: Windows Server 2012 R2
## Screenshots

![console](https://i.gyazo.com/b0c03d8cbc1077b10dda65589a6a0c78.png)
![error](http://img.prntscr.com/img?url=http://i.imgur.com/PTginX8.png)

**Comment by Forge-Media** [comment]
Seeing the same:
http://i.imgur.com/RMq64Jt.png

## Your Environment

Daemon version used: 265
Environment name and version: Node.js v5.11.0, Version 50.0.2661.94 m (64-bit)
Operating System and version: CentOS Linux release 7.2.1511 (Core)

**Comment by JamyDev** [comment]
Just checking ked, seems like we didn't add the getPlugins permission to our config. Will fix!

**Comment by JamyDev** [comment]
Fix deployed!
