### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by Moo464** [SpaceCP/Bugs#22]
I've tried to download the Daemon but I get this Error:
![2015-12-13_14-30-35](https://cloud.githubusercontent.com/assets/16258566/11767198/1bc1d442-a1a6-11e5-88ab-9e0c7e1b91ec.png)

I also tried to download it with --no-check-certificate but that also won't work.

**Comment by JamyDev** [comment]
Try this link: https://dl2.spacecp.net/houston/houston.zip

**Comment by Moo464** [comment]
Nice, this link works fine. Will this link be updatet everytime there is a new houston.zip? =)

**Comment by JamyDev** [comment]
Yes, it's the same location as the other link, just without CloudFlare.

**Comment by Moo464** [comment]
Maybe you could insert a little notice in the Daemon installer with this tipp =)

**Comment by JamyDev** [comment]
I've removed the whole CloudFlare stuff, it causes more problems than anything

**Comment by Moo464** [comment]
:'D Okay. Thanks for that!
