### ISSUE TITLE
Make a player op does not work

### ISSUE THREAD

**Issue by Moo464** [SpaceCP/Bugs#23]
I'm running a spigot server and if I try to make a player op it won't work.

Console keeps clear.

**Comment by JamyDev** [comment]
I removed your image to protect the ip of your player. Thanks for the report.

**Comment by Moo464** [comment]
A small addendum, if I make a player an op via the console, it shows it as op at the start page and the users page.

**Comment by jithatsonei** [comment]
I had this one before, It would seem me pushing ctrl-c would suddenly have all the messages flow in; this could be coincidental or actually an effect of it. Will test further in that regard.

**Comment by wizdude** [comment]
just in case it's related - if you change the player's game mode in the panel, it does actually change, but the player is not notified and nothing appears in the logs. the same does not occur with vanilla minecraft.

**Comment by MiniDigger** [comment]
I would guess that this is intended. On vanilla there is not plugin. So houston uses the vanilla commands and thats where the message come from. On bukkit, we got a houston plugin which can do things silently. 
If I am right I would vote for some kind of logging of the houstonbukkit plugin to avoid confusion.

**Comment by wizdude** [comment]
@MiniDigger that comment is applicable to my other ticket #46 but not this one. when you click on OP the player isn't opped. but thanks for explaining the difference in the implementations. knowledge is power.

**Comment by MiniDigger** [comment]
@wizdude this is not knowledge, this is just a wild guess at my end ^^

**Comment by tlaundal** [comment]
The panel never sends the method call to the server it seems. At least HoustonBukkit never recieves it, @JamyDev

**Comment by tlaundal** [comment]
Making a player OP works on Vanilla, but not on Bukkit

**Comment by Antariano** [comment]
Finally fixed this one ;)
