### ISSUE TITLE
Daemon Connection

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#24]
When I turn off the daemon, it takes the panel a while to notice. Also, when the server runs, there is no information in the console or in ram/cpu status.

System Specs:
Windows 10 Pro
Chrome 64 bit
Java 1.8_66

**Comment by JamyDev** [comment]
I just pushed a change that should fix the reconnection failures. Let me know how this works

**Comment by SAIYAN48** [comment]
Is it just panel-side? Right now my server is running yet the panel says it's off.

**Comment by JamyDev** [comment]
Does it say `stopped` or `No connection`?

**Comment by SAIYAN48** [comment]
Stopped

**Comment by JamyDev** [comment]
Try restarting the daemon

**Comment by SAIYAN48** [comment]
Done. Still nothing.

**Comment by SAIYAN48** [comment]
Now it works perfectly!
