### ISSUE TITLE
Can't register for an account!

### ISSUE THREAD

**Issue by TheSander562** [SpaceCP/Bugs#246]
## Expected Behavior
I want to register so i expected that the register button would work.

## Current Behavior
The register button doesnt work.

## Steps to Reproduce (for bugs)
1. Go to the register page.
2. Fill in the empty spots.
3. Click on the button.
4. Button doesn't work.

## Context
I really want to register so i can setup my own server.

## Your Environment
* Daemon version used: I dont know
* Server OS (eg. Ubuntu 16.04): Windows?
* Server environment (e.g. node.js 5.4): I dont know
* Client browser (e.g. Chrome 39): I used many, like chrome, internet explorer, opera.

* Other info:

**Comment by Willsr71** [comment]
This is likely due to user registration being disabled according to the message here
![image](http://image.prntscr.com/image/153e1c36485b45f7be155f8d2d3fb831.png)

**Comment by TheSander562** [comment]
i didnt get that message

**Comment by Willsr71** [comment]
That message does not appear on the page, it is in the console. What message did you get?

**Comment by Willsr71** [comment]
That message does not appear on the page, it is in the console. What message did you get?

**Comment by TheSander562** [comment]
Nothing, i am just stuck at that page, i can press it manny times, but nothing happens

**Comment by ukdyl94** [comment]
As stated above by @Willsr71 User registration is disabled, which would be why "nothing happens".

**Comment by Willsr71** [comment]
Check your console. That is where the message should be.

**Comment by TheSander562** [comment]
![image](https://cloud.githubusercontent.com/assets/14059770/25046371/61832b1e-2131-11e7-830d-dd3338e91a15.png)

**Comment by TheSander562** [comment]
I put in my email ofcourse, but it says bad request.

**Comment by Willsr71** [comment]
Expand the >Object lines below the requests so that they look like the original image I posted.

**Comment by TheSander562** [comment]
![image](https://cloud.githubusercontent.com/assets/14059770/25046521/31cf0ee6-2132-11e7-955c-5606f6212553.png)

**Comment by Willsr71** [comment]
The message object says "User registration disabled." Therefore, user registration is disabled.

**Comment by TheSander562** [comment]
Okay

**Comment by JamyDev** [comment]
Registration has been disabled for now.
