### ISSUE TITLE
https://app.spacecp.net/#/auth/register not working 

### ISSUE THREAD

**Issue by XxPoNaGeXx** [SpaceCP/Bugs#247]
The https://app.spacecp.net/#/auth/register page ks not working, I typed all my info in and then press register and nothing happens 

## Expected Behavior

It should register my account

## Current Behavior

Nothing happens when I press register

## Steps to Reproduce (for bugs)

1. Go to https://app.spacecp.net/#/auth/register
2. Type info
3. Press register
4.

## Your Environment

* Daemon version used:
* Server OS (eg. Ubuntu 16.04):
* Server environment (e.g. node.js 5.4):
* Client browser (e.g. Chrome 39):

* Other info:

**Comment by MiniDigger** [comment]
registering is disabled, see #246
