### ISSUE TITLE
Scheduler duplicates message

### ISSUE THREAD

**Issue by marcdif** [SpaceCP/Bugs#25]
When using the player chat scheduler configured down below, it duplicates the message as seen in the second picture.
![screen shot 2015-12-13 at 3 42 51 pm](https://cloud.githubusercontent.com/assets/6166238/11769222/35b364b0-a1b0-11e5-80b0-422568253062.jpg)
![screen shot 2015-12-13 at 3 41 52 pm](https://cloud.githubusercontent.com/assets/6166238/11769225/3859e270-a1b0-11e5-8248-1ef28979087e.jpg)

**Comment by tlaundal** [comment]
This is a HoustonBukkit issue.
Basically the event was handled two places. Fixed in commit 4b481708.
