### ISSUE TITLE
Colored MOTD having display issues

### ISSUE THREAD

**Issue by Flakenstine** [SpaceCP/Bugs#26]
On server restart the MOTD will have more color codes then it started with and will often cause issues with the original formatting.
![Imgur](http://i.imgur.com/ZKQZdyp.png)

**Comment by JamyDev** [comment]
After an hour of debugging I found the problem. The `properties` module we use doesn't encode that character (and a few others) correctly.

**Comment by JamyDev** [comment]
A side problem is that it also encodes a backslash, so we can't provide that code either...

**Comment by JamyDev** [comment]
A change has been pushed to fix this, it should be in the next update ;)

**Comment by PetieM** [comment]
This still isn't working for me. Is there something I have to do to force this fix to work or is something still wrong?

**Comment by PetieM** [comment]
This still isn't working for me. Is there something you need to do to force the fix, is there an issue on my end possibly, or is this still broken?

**Comment by JamyDev** [comment]
@PetieM Houston build number, and an example motd please.

**Comment by PetieM** [comment]
Sorry about that - hit submit just a little too soon.

Build is listed as b83155176d848a791659d2f25fd1dac3f92a1f57_160 though if you need something else, let me know. I have another bug to submit but I'd like to verify all is well on my end before doing so. I can say that it doesn't detect any updates but it's also entirely possible an update failed on my end.

MOTD Samples:
**Panel:** Â§7Â§l[ Â§3Â§lVGCraft Test Server Â§7Â§l]
**server.properties:** \u00C2\u00A77\u00C2\u00A7l[ \u00C2\u00A73\u00C2\u00A7lVGCraft Test Server \u00C2\u00A77\u00C2\u00A7l]
**Original server.properties:** \u00A77\u00A7l[ \u00A73\u00A7lVGCraft Test Server \u00A77\u00A7l]
**Client:**
![screen shot 2015-12-27 at 12 07 30 pm](https://cloud.githubusercontent.com/assets/16453878/12011198/70ed37da-ac92-11e5-9ed6-3b3587788d97.png)

**Comment by JamyDev** [comment]
Try this and set it in the panel: `§7§l[ §3§lVGCraft Test Server §7§l]`

**Comment by PetieM** [comment]
I've tried that a number of times, with and without clearing the field with normal text first. It continues to insert Âs each time.

**Comment by JamyDev** [comment]
Yup, we found the bug. Will be fixed tonight
