### ISSUE TITLE
undefined / null avatar

### ISSUE THREAD

**Issue by jomo** [SpaceCP/Bugs#28]
Developer of @crafatar here.

I was just randomly looking at some logs and noticed requests to [`/avatars/null`](https://crafatar.com/avatars/null) and [`/avatars/undefined`](https://crafatar.com/avatars/undefined) coming from spacecp. Both are valid usernames, but chances are quite low these requests were intended.
User Agents were recent versions of Google Chrome and Safari.

_Maybe related to the issue shown in #18?_

Hope this helps you guys :)

**Comment by Antariano** [comment]
Yeah, pretty sure those two are related :) Thanks!

**Comment by JamyDev** [comment]
Thanks for the report, we have fixed this issue and will deploy it in our next update!
