### ISSUE TITLE
Cauldron Bukkit/Forge - Detected as Vanilla

### ISSUE THREAD

**Issue by Katelyn-SN** [SpaceCP/Bugs#34]
I am unable to enable bukkit support on the panel after enabling bukkit it states the following:

We detected that your server config is set to bukkit but is running vanilla.

Would you like to switch the config to use vanilla instead?

However when selecting "Keep using Bukkit" it goes into a working screen which never goes away.

**Comment by Antariano** [comment]
Thanks! Im guessing the cauldron logs are confusing it. But the loading screen is a bug.

**Comment by JamyDev** [comment]
Part 1, Cauldron being counted as a vanilla-like has been fix and is queued for the next deploy.

**Comment by Antariano** [comment]
Refer to https://github.com/SpaceCP/Bugs/issues/80 for the second part of this issue
