### ISSUE TITLE
Properties File

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#36]
- Editing the whitelist property doesn't effect the server.
- Changing the players just resets back to 20, the config file and the properties file.
- Ram & CPU Monitors are not working.

All I have noticed so far.

Sincerely, JTheComputerNerd

**Comment by jithatsonei** [comment]
Please read the SpaceCP bugs topic on the forums, and the readme in the repository before reporting bugs please :|

**Comment by jithatsonei** [comment]
Duplicate (first point) in #6

**Comment by Antariano** [comment]
Closing for now, if any of these issues still persist, stick em in separate issues.
