### ISSUE TITLE
Full shutdown

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#37]
When stopping the server either from the Panel or by shutting off daemon, kill the Java process so that the server is completely off.

**Comment by ghost** [comment]
Stopping the server in the panel kills the Java process to my knowledge but closing daemon definitely doesn't stop the process.

**Comment by JamyDev** [comment]
OS?

**Comment by ghost** [comment]
For me it's Windows 10 64 bit

**Comment by JamyDev** [comment]
Using the normal cmd?

**Comment by JamyDev** [comment]
Current suggestion, don't click the X, use CTRL+C then Enter. That will shut it down safely.

**Comment by JamyDev** [comment]
I have a solution for this, however Windows will unconditionally close the node process after 10 seconds, which means that if your servers take long to shutdown I might have to force kill them..

**Comment by JamyDev** [comment]
A fix will be pushed as soon as I've seen Star Wars

**Comment by JamyDev** [comment]
If you want you can try out the dev version already and let me know how it works, [link](https://dl.spacecp.net/houston/houston_162_1450342879.zip)

**Comment by SAIYAN48** [comment]
Now the daemon has no panel connection and it allocates 1GB of ram instead of the assigned 10GB.

**Comment by JamyDev** [comment]
Could you please provide me with the config file for the server that has the wrong amount of ram? It's located in config/servers/servername.json

**Comment by SAIYAN48** [comment]
Sure. http://pastebin.com/zLCNM6Gq
