### ISSUE TITLE
Maximum player count does not work

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#38]
when I created my server I accepted the default of 10 slots. the panel shows 10 slots, however the server.properties is configured for 20.

unsure if this is a panel or houston problem. currently running houston beta 5.

**Comment by Antariano** [comment]
Thanks, we'll look into it

**Comment by jithatsonei** [comment]
I would assume this is an Houston addon issue since it is not properly updating the mc server slot coint

**Comment by JamyDev** [comment]
Or the slot count was updated in the server.properties and wasn't properly corrected by Houston. Either way, I'll look into it ;)

**Comment by wizdude** [comment]
additional information - the panel dashboard shows 20 players, the banner shows 20 players, but server settings shows 10 players - which is what i originally configured during deployment.

**Comment by JamyDev** [comment]
@wizdude Can you send me the config file for that server? it's in `<houstondir>/config/servers/<server>.json`

**Comment by wizdude** [comment]
[spacecp-test-server.txt](https://github.com/SpaceCP/Bugs/files/67926/spacecp-test-server.txt)

renamed from .json to .txt because github doesn't like json :-)

**Comment by wizdude** [comment]
i'm guessing you've changed something at the panel end - i deployed a new test server last night, and it works. of most importance is the server config file for the new server contains "limits - maxPlayers: 10" and it's reporting back everywhere correctly, but the first two initial servers I spun up (vanilla and spigot) are missing this in the config file as you can see.

i did nothing different when setting up my new third test server.

**Comment by wizdude** [comment]
additional notes: if i increase the number of players (on my new third test server), it appears correctly in the panel and in the <server>.json file, but does not write to server.properties. if i stop and start the minecraft server via the panel, server.properties is updated with the correct value, however I have to physically refresh my browser screen in order to get the updated number of players count to display on the panel.

**Comment by JamyDev** [comment]
I'm not sure if I was able to fix this or not. Can you give it a try and let us know?

**Comment by tlaundal** [comment]
With Bukkit and Vanilla, SpaceCP resets the max player field to 20 if you change the server.properties. Watching the file as the server starts up reveals that the field is set to blank during startup, and set back to 20 when the server has started. This is if you never touch the `Maximum player count` field under server details.

If you update the player count by `maximum player count` field in server details, and press the update button (which doesn't give any feedback), and restart the server, the server will have the correct max player count. However, the players widget displays the wrong number until you reload the panel page.

**Comment by tlaundal** [comment]
I suggest the following to fix this:
- Remove `max-players` from `server.properties` config on panel, but keep the config option in server details.
- Update the player widget and banner when maximum players have been changed.

**Comment by tlaundal** [comment]
This is really fixed, more or less.
