### ISSUE TITLE
[Panel] banner contains incorrect port number

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#39]
I run multiple minecraft servers at home, so I usually provision these using SRV records with the appropriate port number to be used.

i've configured my spacecp test server with a non-default port number during the setup. the panel correctly shows the server port and it has been provisioned on my host with the correct port number.
i can connect to my minecraft server using this port number with no issues.

the "banner" on the panel, however, just shows the default 25565 port and thus reports that my server is "offline".

**Comment by Antariano** [comment]
Is this still happening? If yes, please PM us your server name on the forums so we can take a closer look.

**Comment by wizdude** [comment]
all fixed!

**Comment by wizdude** [comment]
when creating servers, the port on the banner always goes to 25565 regardless of the settings.
once the server is up and running, you have to REFRESH your browser to fix the issue.

while this is now a cosmetic issue, it would be nice to have the correct port number in the banner in the first place. refreshing the browser in a control panel scenario doesn't immediately seem logical when you are clicking from tab to tab dynamically and everything else refreshes.

**Comment by Antariano** [comment]
I see what's happening now. The properties on the server and database are basically missing a trigger and only "sycing" on refresh. Thanks, that helps!

**Comment by Antariano** [comment]
Closing in on a fix
