### ISSUE TITLE
Incorrect bug and home URL in package.json

### ISSUE THREAD

**Issue by jithatsonei** [SpaceCP/Bugs#40]
This one is being nick picky but oh well :P. Not too much of a bug just a gripe

Line 34-36 in package.json

``` json
  "bugs": {
    "url": "https://github.com/Antariano/SpaceCP-Daemon/issues"
  },
```

This should be linking to https://github.com/SpaceCP/Bugs/issues/ instead :V (And _TECHNICALLY_ line 37 the homepage value should be set to https://spacecp.net)

it's the little things in life that bug us the most aye ;p

**Comment by Antariano** [comment]
Fixed in build 6 that will be deployed this weekend.
