### ISSUE TITLE
[DAEMON] Deamon connection taking ages

### ISSUE THREAD

**Issue by MiniDigger** [SpaceCP/Bugs#42]
This is related to #12 
I ran into a similar issue again. I stopped houston, run node update, started houston and one server gets stuck

```
- random: [22:11:14 INFO]: Cactus Growth Modifier: 10HI
0%
- random: [22:11:14 INFO]: Cane Growth Modifier: 100%
- random: [22:11:14 INFO]: Melon Growth Modifier: 100%
- random: [22:11:14 INFO]: Mushroom Growth Modifier: 100%
- random: [22:11:14 INFO]: Pumpkin Growth Modifier: 100%
- random: [22:11:14 INFO]: Sapling Growth Modifier: 100%
- random: [22:11:14 INFO]: Wheat Growth Modifier: 100%
- random: [22:11:14 INFO]: NetherWart Growth Modifier: 100%
- random: [22:11:14 INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
- random: [22:11:14 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
- random: [22:11:14 INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
- random: [22:11:14 INFO]: Random Lighting Updates: false
- random: [22:11:14 INFO]: Structure Info Saving: true
- random: [22:11:14 INFO]: Sending up to 10 chunks per packet
- random: [22:11:14 INFO]: Max Entity Collisions: 8
- random: [22:11:14 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
- random: [22:11:14 INFO]: Max TNT Explosions: 100
- random: [22:11:14 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
- random: [22:11:14 INFO]: Preparing start region for level 0 (Seed: 6544173717758205368)
- random: [22:11:15 INFO]: Preparing spawn area: 12%
- random: [22:11:16 INFO]: Preparing spawn area: 61%
- random: [22:11:17 INFO]: Preparing spawn area: 98%
- random: [22:11:17 INFO]: Preparing start region for level 1 (Seed: 8102884873540273457)
- random: [22:11:17 INFO]: Preparing start region for level 2 (Seed: 8102884873540273457)
- random: [22:11:18 INFO]: [Houston] Enabling Houston v1.0-SNAPSHOT
- random: [22:14:50 INFO]: UUID of player MiniDigger is 2c771d16-f492-4f7a-adb7-61c38a9c9bfb
```

as you can see, the server itselfs it running but houston is blocking it. (I get kicked with a ReadTimeout, which does not show up in the consol, since the server is hanging)
in the panel it says starting and all sort of thing broke, since the server isn't responding.

Well as I am writing this the plugin connected....

```
- random: [22:11:18 INFO]: [Houston] Enabling Houston v1.0-SNAPSHOT
- random: [22:14:50 INFO]: UUID of player MiniDigger is 2c771d16-f492-4f7a-adb7-61c38a9c9bfb
- random: [22:19:40 INFO]: [Houston] Houston@1.0-SNAPSHOT
- random: [22:19:40 INFO]: [Houston] dynmap@2.2-1118
- random: [22:19:40 INFO]: [Houston] TCActionBlocks@1.3
- random: [22:19:40 INFO]: [Houston] WorldEdit@6.1;no_git_id
- random: [22:19:40 INFO]: [Houston] Multiverse-Core@2.5-b691
- random: [22:19:40 INFO]: [Houston] BKCommonLib@1.66-SNAPSHOT
- random: [22:19:40 INFO]: [Houston] TCHangRail@1.0
- random: [22:19:40 INFO]: [Houston] SignLink@1.35-SNAPSHOT
- random: [22:19:40 INFO]: [Houston] VerticalRails@1.0.3
- random: [22:19:40 INFO]: [Houston] Train_Carts@1.75-SNAPSHOT
- random: [22:19:40 WARN]: [Houston] Running under unsupported Bukkit version, this might cause problems.
- random: [22:19:40 INFO]: Server permissions file permissions.yml is empty, ignoring it
- random: [22:19:40 INFO]: Done (506.634s)! For help, type "help" or "?"
- random: [Houston] Connetion daemon <-> Bukkit established.
- random: [22:19:40 INFO]: [Houston] Connection to Houston established
```

I freed up my vps so ressources are not the problem (only have ram used an cpu load at around 40%). I don't have any network intesive tasks running too, which could have caused this problem.

**Comment by JamyDev** [comment]
Interesting, can you upload a zip file of all the plugins you have on the server? There's probably a conflict.

**Comment by MiniDigger** [comment]
Well, thats funny:
I had an issue at the server with a friend getting disconnected all the time (error message: you logged in from a different place) and to debug it I disabled all plugins: http://puu.sh/m0ypm/7289a344dc.png
Bukkit loads only houston (this is what /pl tells me). How does Houston now which plugins are installed?

**Comment by JamyDev** [comment]
Houston always makes sure houstonbukkit.jar is linked.

**Comment by JamyDev** [comment]
I'm going to add a config option to not do that in the next release.

**Comment by MiniDigger** [comment]
houstonbukkit is loaded, sorry. But it is the only one thats loaded. But it tires to submit all plugins to the panel. And it seems to has trouble doing that since they are disabled (renamed) and bukkit didn't load them.

**Comment by JamyDev** [comment]
Odd, @narrowtux Any ideas?

**Comment by MiniDigger** [comment]
As far as I can tell houston tries to submit all plugins that are listed in /<server>/houston/ManagedPlugins/. This is the content of the file for the plugin BKCommonLib:

```
{"file":"/home/spacecp/servers/random/./plugins/BKCommonLib.jar.old","active":true,"wasInstalledWith":[]}
```

it noticed, that the plugin was renamed but it still thinks that it is acitve...
maybe houstonbukkit should update this folder (the server is started now and the content of managedplugins wasn't updated to note, that the plugins are disabled)
the files where modifed at 22:19:40, the time houston submitted the plugins to the panle after hanging for 8 minutes.

**Comment by narrowtux** [comment]
Ok, so the way Houston handles plugins expects you to keep the file names as they are. I will try to make this possible later on, but for now, just `deactivate` plugins from SpaceCP instead of renaming them.

**Comment by MiniDigger** [comment]
is the delay at start also caused by me disabling plugins manually?

**Comment by narrowtux** [comment]
Can you try if it happens with a completely fresh server?

MiniDigger notifications@github.com schrieb am Sa., 19. Dez. 2015 um
17:39 Uhr:

**Comment by MiniDigger** [comment]
I already tried reproducing it when it bug first occured. It seems to 
only occur after a houston update.

Am 19.12.2015 um 17:52 schrieb Moritz Schmale:

**Comment by JamyDev** [comment]
Could you still send me a zip file of your plugins folder as well as your Spigot version so I can give it a shot locally?

**Comment by MiniDigger** [comment]
I have send you a pm (on the forums)

**Comment by MiniDigger** [comment]
today it happend without updating houston. I just stopped houston, started it again and I have the same symptoms as above. So it is not related to the houston update process.

**Comment by tlaundal** [comment]
Are you still having this problem with the latest build (6), @MiniDigger?

I think this is fixed.

**Comment by MiniDigger** [comment]
didn't had a chance to test it yet, will have time on the weekend

**Comment by tlaundal** [comment]
I think this is ready to be closed, unless @MiniDigger has some more info
.

**Comment by MiniDigger** [comment]
going ahead and closing it. If I experience anything related I will come back
