### ISSUE TITLE
Setup takes forever

### ISSUE THREAD

**Issue by SAIYAN48** [SpaceCP/Bugs#43]
After Daemon reinstall, the panel is stuck on Step 5.
Chrome 48 Beta
Windows 10 Pro build 1511
Java 1.8_66
Houston: 166

**Comment by MiniDigger** [comment]
Please read the readme (https://github.com/SpaceCP/Bugs/blob/master/README.md) before filing an issue. You should provide more information about your browser and the system the daemon is running on

**Comment by jithatsonei** [comment]
(AKA elaborate why it's 'stuck')

**Comment by SAIYAN48** [comment]
If I knew why it's stuck, then I'd fix something. Nothing happens at step 5, just the "we are setting up your server.

**Comment by JamyDev** [comment]
See houston console, or the chrome console..

**Comment by SAIYAN48** [comment]
Houston didn't say anything, just that it was running.

**Comment by jithatsonei** [comment]
Chrome dev console as well..

**Comment by SAIYAN48** [comment]
Nothing in there either.

**Comment by SAIYAN48** [comment]
UPDATE: Server is running. Panel still thins it has no connection to server and memory is 1GB. (Using latest Houston)

**Comment by jithatsonei** [comment]
This would be an issue that belongs to the forums then I believe

paging @Antariano or @JamyDev to confirm

**Comment by JamyDev** [comment]
Yeah seems like an isolated incident. However I hope I can get a way to reproduce the getting stuck on setup part as that seems to happen rather often.

**Comment by tlaundal** [comment]
This is probably related to #98, I experienced something similar.

**Comment by Antariano** [comment]
Closing.
