### ISSUE TITLE
RAM/CPU always shows zero.

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#47]
on my vanilla and spigot test servers, the panel always shows zero for RAM and CPU - both on the dashboard and in the top right hand corner.

**Comment by MiniDigger** [comment]
if I recall this bug should be fixed allready...
what houston version are you running on? You can try node update houston to update it.

**Comment by Antariano** [comment]
Apparently this is happening again, we're investigating

**Comment by JamyDev** [comment]
Fixed.

**Comment by wizdude** [comment]
it was working - but now it's stopped and all servers show zero counters again
