### ISSUE TITLE
[Daemon/Panel] No RAM / CPU / Player Stats for custom modpacks 

### ISSUE THREAD

**Issue by xCausxn** [SpaceCP/Bugs#5]
Currently using Tekkit Legends

Server is online and running however there does not seem to be any player count / ram / cpu stats being sent through.

The events however are being received all 0

**Comment by JamyDev** [comment]
Get me a way to reproduceit and I'll fix it :P

**Comment by JamyDev** [comment]
Since a lot of fixes to stats have gone out, I'll count this as resolved until proven otherwise
