### ISSUE TITLE
file manager save never completes

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#53]
when using the file manager to edit a file, when you click on "save" you get a spinning orange circle and the operation never completes. you need to click on "close" to close the window.

the file does successfully save onto the file system. i have made multiple changes to files and confirmed that they do write back correctly.

even stranger is that you can continue to edit the file and then click on the same spinning orange circle and the file will correctly save again, although the spinning orangle circle never changes to anything else.

this issue does not appear to be related to any specific web browser. fault confirmed in both firefox and chrome.

**Comment by Antariano** [comment]
Already fixed in Build 6 :)
