### ISSUE TITLE
Plugins automatically toggled to disable upon login.

### ISSUE THREAD

**Issue by qckcat** [SpaceCP/Bugs#55]
No matter what, every time you log into SpaceCP (running the latest spigot) and you go to your plugins page they will be set as disabled (even though they are enabled and running.

http://i.imgur.com/4WCP9Sc.png

Steps to recreate:
1. Create a server running the latest spigot/bukkit build.
2. Install at least one plugin.
3. Set it to enabled in the plugin manager.
4. Log out and back into SpaceCP.
5. Voila, you are greeted with the disabled message.

**Comment by wizdude** [comment]
i can concur with your findings and see the exact same problem, however i can also replicate it when restarting the minecraft server - no logout/login of spacecp required.

my version of the steps:
1. Create a server running the latest spigot build.
2. Install at least one plugin.
3. Set it to enabled in the plugin manager.
4. Restart the spigot server
5. Voila, you are greeted with the disabled message.

**Comment by tlaundal** [comment]
This is fixed in build 6
