### ISSUE TITLE
Chat being doubled on the panel

### ISSUE THREAD

**Issue by greatman** [SpaceCP/Bugs#57]
When someone chat ingame, the chat window in the panel doubles the text.

![image](https://cloud.githubusercontent.com/assets/95754/11922558/0ce157f2-a766-11e5-8703-032d611864be.png)

The ingame client: 
![image](https://cloud.githubusercontent.com/assets/95754/11922581/29c74ab6-a766-11e5-9527-0be5b2183deb.png)

**Comment by JamyDev** [comment]
Do you have any schedules set?

**Comment by JamyDev** [comment]
Also I'm assuming this is Bukkit/Spigot. I'll investigate...

**Comment by tlaundal** [comment]
Not reproducible with the new unreleased houstonbukkit.jar on Spigot.
