### ISSUE TITLE
logs only visible since server restart for current day

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#58]
if you restart a server, the logs are only visible for the current day.
previously we could see the logs going back multiple days.

in the test I performed, the logs on the panel were showing from latest.log and 2015-12-22-1.log.gz. i would have expected the ability to see back further, even if that requires clicking on a "previous logs" or "older logs" button at the bottom of the log viewer to go back into a previous log file.

**Comment by wizdude** [comment]
additional information: after restarting the minecraft server from the panel, all the logs are visible again. going to retest this again on the other instances.

**Comment by wizdude** [comment]
![space-cp-1](https://cloud.githubusercontent.com/assets/7669231/11932186/83028e42-a847-11e5-8a9d-3e92f59d37c5.PNG)
![space-cp-2](https://cloud.githubusercontent.com/assets/7669231/11932190/878e298a-a847-11e5-84e9-f922535b57ea.PNG)

first screen shot - before server restarted
second screen shot - after server restarted

all of the log entries have now reappeared.

i believe this is related to restarting houston. when houston is restarted, only the currently and one log back are visible until the individual minecraft servers are restarted.

**Comment by tlaundal** [comment]
This seems to be fixed. Please reopen the issue @wizdude if you are able to reproduce it again
