### ISSUE TITLE
cannot delete elements from schedule

### ISSUE THREAD

**Issue by wizdude** [SpaceCP/Bugs#59]
it's not possible to delete an element/item from any part of a schedule when creating it.

for example, if I click on the "+" underneath "Conditions (optional)" and decide i don't want to choose anything, there is no way to remove this element/item i have just added and then it's impossible to create the schedule because "There are conditions lacking data".

you have to manually select something to complete the setup of an element/item before you have the "remove" option available.

this becomes very frustrating - especially if you incorrectly thought you clicked on a field to edit and start entering text with spaces. each 'space' becomes the same as clicking on the "+" button and before you know it you have a full list of "choose" items which you have to fill in to remove.

**Comment by Antariano** [comment]
This has been improved in Build 6
