### ISSUE TITLE
[PANEL] Whitelist doesn't update

### ISSUE THREAD

**Issue by MiniDigger** [SpaceCP/Bugs#6]
When removing players from the whitelist the list doesn't update
https://gyazo.com/c13f051c9089250ffe1d183b7b31a55a
It does remove the player tho
![Image](http://puu.sh/lQQog/83629040b9.png)

**Comment by MiniDigger** [comment]
Correction: It does NOT remove the player from the whitelist on the server

**Comment by tlaundal** [comment]
Using the updated houstonbukkit.jar (which isn't released yet) this seems to work, @JamyDev.
I think it worked last time I tried with the old houstonbukkit.jar too.
