### ISSUE TITLE
Panel and logs don't use system time of deamon

### ISSUE THREAD

**Issue by Jenjen1324** [SpaceCP/Bugs#63]
As the title says.
It's a lot smarter to use the system time of the deamon/houston because that's localized. I can't say if Schedules work on deamon time but I guess they don't.
It also makes it quite confusing when comparing times in the logs and looking at the console.

**Comment by JamyDev** [comment]
Good idea!

**Comment by JamyDev** [comment]
Schedules should run on daemon time. I don't think there are a lot of issues in regards to this except for timestamps that display on the panel.

**Comment by tlaundal** [comment]
On Windows it seems all the times are in the system time of the daemon, I've only tested this when using the panel on the same machine as the daemon, however, with time zone UTC+1.

**Comment by Jenjen1324** [comment]
Hm weird, the times are correct for me now as well. If it actually takes the timezone of the server you can close this, but if it takes the time of the CP or WebBrowser then I don't think this issue is resolved.

To add to that, I'm in UTC+1 as well

**Comment by JamyDev** [comment]
The panel is on a machine with a timezone different from UTC+1 so this seems like it's intended behaviour.
