### ISSUE TITLE
Houston started but in cp it loops "Waiting for daemon to start."

### ISSUE THREAD

**Issue by faneQ123** [SpaceCP/Bugs#64]
I've tryed everithing. It just stays like that...

![houstin2](https://cloud.githubusercontent.com/assets/11634089/11968521/e04bdfda-a915-11e5-9eaf-2b067b2c63a6.png)
![houston1](https://cloud.githubusercontent.com/assets/11634089/11968524/e58dfece-a915-11e5-8817-6f4237bccfea.png)

**Comment by jithatsonei** [comment]
An external factor is preventing Houston from making a connection to SpaceCP. Check for anything that could be blocking it like firewalls and be sure port 35566 is fowarded

**Comment by vamoosehd** [comment]
I have the same issue. I have disabled all firewalls opened the port and everything still stuck on loop

**Comment by faneQ123** [comment]
Firewall disabled , port forwarded. Still not working

**Comment by faneQ123** [comment]
![firewall](https://cloud.githubusercontent.com/assets/11634089/11977437/959d2522-a98b-11e5-8350-099f4b8fae68.png)
![firewall2](https://cloud.githubusercontent.com/assets/11634089/11977442/9a710ec4-a98b-11e5-8da6-3c4d599e814b.png)

**Comment by faneQ123** [comment]
I've managed to start it by changing the houston folder from /var/ to /home/. Now it works

**Comment by JamyDev** [comment]
That wouldn't be the problem. Also can I note that it's best to not run Houston as root?
