### ISSUE TITLE
"Houston needs to be bootstrapped first." Missing Files?

### ISSUE THREAD

**Issue by ncronin** [SpaceCP/Bugs#65]
I'm getting the following error, installed on a fresh Ubuntu 14.04 droplet:

https://gist.github.com/ncronin/6c5d38d01ca54d226056

**Comment by NEXUS2345** [comment]
Please follow this guide: https://forums.spacecp.net/topic/226/setting-up-on-spacecp

Basically, you missed out an important command in the setup process.

**Comment by ncronin** [comment]
I did follow the instructions and it gave me that recurring error.

**Comment by NEXUS2345** [comment]
You need to run this command in the directory houston was extracted to: 

node houston bootstrap -i 56672d1f315449d960ad8c60 -k 640ded05f3d5bdfd6e148d1f6d312ec445cc5915a5af9814f2f705d9528a97eb

**Comment by jithatsonei** [comment]
Please do not run the cmd posted above. Doing so will link Houston to a different SpaceCP acct.

Be sure you did add the daemon, and ran the cmd as posted here:

![image](https://cloud.githubusercontent.com/assets/12538482/11990315/55127e8a-a9d1-11e5-8744-19b93bf770bf.png)

NOTE: If you are on windows, do npm install --silent **THEN** run the node houston bootstrap cmd

**ALSO NOTE THAT THE BOOTSTRAP CMD SPACECP GIVES YOU IS UNIQUE TO YOUR ACCT**

**Comment by ncronin** [comment]
My mistake, Node was incorrectly setup on my machine and didn't install the bootstrap when I thought it had. Thanks everyone!
