### ISSUE TITLE
Input field blocks text

### ISSUE THREAD

**Issue by harryjamesuk** [SpaceCP/Bugs#66]
Hello,

Just wanted to report a very minor issue, but the Input Field for the chat ends up blocking the text, meaning you are unable to see the last message sent as shown below:

![](https://gyazo.com/33caf86fc8cabc56b428b07acb4128d7.png)

Hopefully this issue can be fixed soon :)

**Comment by wizdude** [comment]
some additional notes: not only does the input field cover part of the chat, but when the chat continues, the box gets a scroll bar and does not scroll, so you have to manually scroll the window

![chat-scrolls](https://cloud.githubusercontent.com/assets/7669231/11998799/cfdafb38-ab02-11e5-9b1d-7f2766a8bab4.PNG)

**Comment by Antariano** [comment]
Fixed in build 6, to be deployed.
