### ISSUE TITLE
Text in houston console is doubled

### ISSUE THREAD

**Issue by tlaundal** [SpaceCP/Bugs#69]
This happens for me on Windows 10, using newest Houston release, running in bash on ConEmu. The server is running newest Spigot with the new unreleased houstonbukkit.jar.

When I do `node houston server <server name> cli`, I get the Houston server console, but all text I write comes up doubled. See this screencap:
![doubletext](https://cloud.githubusercontent.com/assets/817001/12003841/3f7f99a8-ab30-11e5-8eba-fd3755881042.gif)
Here you see me writing `.list`, which shows up as `..lliisstt` and `stopp`. When I press backspace once, and thus remove the last `p`, the double characters disappears.

**Comment by JamyDev** [comment]
YAY for windows >.>
