### ISSUE TITLE
Can install npm because of plesk

### ISSUE THREAD

**Issue by ntimo** [SpaceCP/Bugs#71]
Hello,

when I try to install npm witch is needed for the deamon. Ubuntu says it will remove all the plesk services. So I can't use spacecp on my server. How can I fix this?

**Comment by JamyDev** [comment]
You could try compiling npm from source, however it's weird that plesk would uninstall just due to you installing npm. Have you tried googling this behaviour?

**Comment by ntimo** [comment]
I haven't tried that yet. Also I just read this http://gnetos.de/2015/06/15/install-nodejs-and-npm-with-plesk/ but its german.

**Comment by JamyDev** [comment]
Please refer to this to install an up to date version of node: https://nodejs.org/en/download/package-manager/

Afterwards install npm manually like this: `curl -L https://www.npmjs.com/install.sh | sh` (from https://github.com/npm/npm#fancy-install-unix)

**Comment by ntimo** [comment]
Ok, I have the latest nodejs. But can I use The SpaceCP Deamon without npm?

**Comment by JamyDev** [comment]
Just install npm using the command provided above. Npm is a core part of any node app, so yes it's needed.
