### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MiniMinerLPs** [SpaceCP/Bugs#73]
Hey! I tried to update and restart houston.
Here is my log: http://hastebin.com/uwizuyikok.coffee

**Comment by JamyDev** [comment]
Just run `node houston start` again...

**Comment by MiniMinerLPs** [comment]
i cannot start houston bcus it's already running... when i try to stop houston the error occours :o

**Comment by JamyDev** [comment]
Well it's running elsewhere, so go to that screen/process and kill it first...

**Comment by MiniMinerLPs** [comment]
Okay, houston is working now. The Servers automatically start but i cannot stop them.... http://prntscr.com/9jf8vc
http://hastebin.com/niqumeyopi.vbs

**Comment by JamyDev** [comment]
Have you refreshed?

**Comment by MiniMinerLPs** [comment]
Working fine! Now the panel says that the analytic servers are down xD http://prntscr.com/9jkkhx
