### ISSUE TITLE
Editing Properties 

### ISSUE THREAD

**Issue by ghost** [SpaceCP/Bugs#74]
I was editing the properties files on SpaceCP when I saved then closed the window. I went to check back and it looked like this.
![screenshot_1](https://cloud.githubusercontent.com/assets/16314086/12013407/e9a77ac0-ad0d-11e5-9021-348c0db219f3.png)

Restarted and still was bugged out, tried to join and the properties were reset to default.

**Comment by Antariano** [comment]
Could you post your server.properties please?

**Comment by tlaundal** [comment]
Could not reproduce with firefox, chrome, IE11 or Edge, with a valid config, at least.
Could not reproduce even when trying to break the config. I tried:
- removing the `=` from an entry
- Inserting all sorts of strange characters, with and without `=` in the entry. I tried: `!@#$%^&*()_+[];',./{}:"<>?`

**Comment by Antariano** [comment]
Will close for now. please reopen if error persists
