### ISSUE TITLE
Player Avatar not displayed

### ISSUE THREAD

**Issue by incognitojam** [SpaceCP/Bugs#77]
It appears that the OPs section of the server console does not seem to be loading player avatars correctly.

![Operator Image](https://i.imgur.com/f4AyYUJ.png)

Right-clicking any of the images and selecting 'Copy URL' gives the same broken URL: https://crafatar.com/avatars/spacecp-minecraft-players-bukkit-dashboard-widget-bukkit-addon-directive?size=24. It appears that the usernames aren't actually being specified when creating these images programmatically.

![Broken URL](https://i.imgur.com/LlCkYoy.png)

Hopefully this can be fixed!

**Comment by Antariano** [comment]
Good catch :) fixing

**Comment by Antariano** [comment]
Fixed in build 7

**Comment by tlaundal** [comment]
Could not reproduce on Firefox
