### ISSUE TITLE
Better handling of EULA agreement on Bukkit

### ISSUE THREAD

**Issue by tlaundal** [SpaceCP/Bugs#82]
When creating a Bukkit server, then panel has no special behaviour for EULA agreement. 

Currently you have to use the file manager and agree to the EULA using the `eula.txt` file, in order to successfully set up a server.

**Comment by Antariano** [comment]
HoustonBukkit needs to conform to vanilla's handling of the EULA. There's events and methods.

**Comment by JamyDev** [comment]
Or we keep that in Houston core itself.

**Comment by tlaundal** [comment]
This needs to stay in Houston. Bukkit doesn't load plugins when the Eula is not agreed. The same goes for sponge (Sponge is coming later, for all curious peepers)
