### ISSUE TITLE
MOTD Formatting codes duplicated

### ISSUE THREAD

**Issue by HexaCubist** [SpaceCP/Bugs#84]
When setting a MOTD with fancy formatting codes (such as §9>§c> §2§lFlareplex 16 §1§l- §6§lARGOS §c<§9<), upon restart Spacecp turns it into 

```
\u00C2\u00A79>\u00C2\u00A7c> \u00C2\u00A72\u00C2\u00A7lFlareplex 16 \u00C2\u00A71\u00C2\u00A7l- \u00C2\u00A76\u00C2\u00A7lARGOS \u00C2\u00A7c<\u00C2\u00A79<
```

Changing that to 

```
\u00A79>\u00A7c> \u00A72\u00A7lFlareplex 16 \u00A71\u00A7l- \u00A76\u00A7lARGOS \u00A7c<\u00A79<
```

still doesn't fix the problem, as spacecp just re-adds the \u00C2

**Comment by tlaundal** [comment]
From the panel this looks like this:

First, you change the MOTD in the config editor:
![before](https://cloud.githubusercontent.com/assets/817001/12063764/7e597a6c-afb4-11e5-8690-7d45013032f6.PNG)
Then, you restart the server, and the config editor now displays this:
![after](https://cloud.githubusercontent.com/assets/817001/12063776/b7b10fc8-afb4-11e5-8314-24f5546560c4.PNG)
Minecraft displays it like this:
![after-minecraft](https://cloud.githubusercontent.com/assets/817001/12063773/9ec58570-afb4-11e5-9b97-5dbbe270912f.PNG)
After another restart, it becomes:
![after-after](https://cloud.githubusercontent.com/assets/817001/12063777/d44f6b5c-afb4-11e5-9aad-5b76e3651831.PNG)

The copied text from the last screenshot is: `ÃÂ§aGreen MOTD`, in `server.properties` it is: `\u00C3\u0082\u00C2\u00A7aGreen MOTD`

If you manually change `server.properties` and put `motd=\u00A7aGreen MOTD`, it turns into `motd=\u00C2\u00A7aGreen MOTD`, this does not happen when starting the server without SpaceCP.

(All this is tested on Vanilla)

**Comment by JamyDev** [comment]
Fixed a thing, find it in build 7 :)
