### ISSUE TITLE
Drop down list of servers doesn't show more than five

### ISSUE THREAD

**Issue by tlaundal** [SpaceCP/Bugs#85]
When managing more than four servers, only the first four will show up on the server selector that comes up when you click the server name.

![servers](https://cloud.githubusercontent.com/assets/817001/12063699/82bd78f2-afb3-11e5-9788-76dd81d527a3.PNG)
![server-list](https://cloud.githubusercontent.com/assets/817001/12063700/82e0a7be-afb3-11e5-9365-4418fef7ab54.PNG)

**Comment by tlaundal** [comment]
Cannot reproduce on Windows. cannot remember if I experienced it on Windows or linux first.

Will close until I've had a chance to test on linux again.

**Comment by JamyDev** [comment]
This seems like a panel issue, so platform really doesn't matter :P
