### ISSUE TITLE
Schedules - Dropdown Menu not showing

### ISSUE THREAD

**Issue by slugshell** [SpaceCP/Bugs#93]
Under Point Schedules the Drop Down Menu for event triggering etc.. "choose" does not show up anymore, tested with Firefox, IE (deleted Cache)
![unbenannt](https://cloud.githubusercontent.com/assets/3969992/12071823/72dcb930-b0c0-11e5-8436-3a49bfce9172.png)

Greetings.
Alex

**Comment by Antariano** [comment]
Hey, is there a stacktrace in your server startup?

**Comment by tlaundal** [comment]
Could not reproduce on Firefox on Windows. Probably a HoustonBukkit issue (You can see he's running Bukkit by the icons on the screenshot).

@slugshell Please look in the server log or houston output for an error with a stack trace, and paste it here.

**Comment by slugshell** [comment]
Hi there, thank you for your response. the issue seems to have resolved it self.. 
Thanks anyway.. 
Greatings. 
slugshell
