### ISSUE TITLE
Entire Players Page Doesn't Update

### ISSUE THREAD

**Issue by qckcat** [SpaceCP/Bugs#94]
The players page remains blank when players joins and disconnects, there is no change to any of it.

Running Spigot 1.8.8 on the latest build of SpaceCP.

(may be considered a duplicate of #76).

**Comment by jithatsonei** [comment]
![image](https://cloud.githubusercontent.com/assets/12538482/12073040/e7a288a2-b0cb-11e5-8eaa-79c0940a1349.png)
Yea dup of #76

**Comment by qckcat** [comment]
Does your also not have any information (or show anything) on the players page?

**Comment by tlaundal** [comment]
This is a duplicate, yes.
