### ISSUE TITLE
Vanilla max players borked

### ISSUE THREAD

**Issue by jithatsonei** [SpaceCP/Bugs#97]
![image](https://cloud.githubusercontent.com/assets/12538482/12073046/2a98bcda-b0cc-11e5-84c7-1fa37b9e13f0.png)
Also doesn't update operators online upon discount (online count goes to 0 however.)

**Comment by tlaundal** [comment]
This is related to #76

**Comment by tlaundal** [comment]
Could not reproduce, max players shows properly for me on Firefox on Windows.

Could you give us some more info?
What web browser, what OS? What OS is the daemon running on? What Minecraft server type and version are you running?

**Comment by jithatsonei** [comment]
Windows 10 on a  latest vanilla release build on the server. Tested on the latest dev build and was still there. (also chrome build 47.0.2526.106)

**Comment by Antariano** [comment]
Can't reproduce this on Build 7, so I'll declare it fixed, we can open it after the deploy tomorrow
